export interface Ebook {
  id: string;
  title: string;
  originalTitle?: string;
  author: string;
  description: string;
  coverUrl: string;
  downloadUrl: string;
  format: "pdf" | "epub" | "mobi";
  language: string;
  year: number;
  fileSize: string;
  category: "textbook" | "grammar" | "vocabulary" | "reading" | "workbook" | "dictionary" | "other";
  level?: "N5" | "N4" | "N3" | "N2" | "N1" | "general";
  tags: string[];
}

export const ebooks: Ebook[] = [
  {
    id: "minna-no-nihongo-2-grammar",
    title: "Minna no Nihongo Shokyu 2: Translation & Grammar Notes",
    originalTitle: "みんなの日本語初級2: 翻訳・文法解説 ; 英語版",
    author: "Surīē Nettowāku",
    description: "Buku pelengkap Minna no Nihongo Elementary 2 dengan penjelasan tata bahasa dan terjemahan dalam bahasa Inggris. Sumber utama untuk pembelajar N5–N4.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Farchive.org%2Fdownload%2Fminnanonihongosh0000unse_s1s0%2F__ia_thumb.jpg&md5=9334a696eb97e86062e2549cf6afcb0c&key=pyuuWO-Lp0QqduR4-ZJXmA",
    downloadUrl: "https://welib.st/md5/9334a696eb97e86062e2549cf6afcb0c",
    format: "pdf",
    language: "Japanese / English",
    year: 2013,
    fileSize: "7.6 MB",
    category: "textbook",
    level: "N5",
    tags: ["Minna no Nihongo", "grammar", "beginner", "classic"],
  },
  {
    id: "minna-no-nihongo-1-workbook",
    title: "Minna no Nihongo Shokyu I: Basic Workbook",
    originalTitle: "みんなの日本語初級I 標準問題集",
    author: "スリーエーネットワーク",
    description: "Buku latihan standar untuk Minna no Nihongo Elementary 1. Berisi soal-soal latihan yang mencakup tata bahasa, kosakata, dan kanji untuk pemula.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2F445d84cfe66d9c12c911cbac68e435e5864e156f4aed8205c628dcde7b494e37.jpg&md5=1b3f2e22c8810a6547fd91a1a580936c&key=LjCWJSYbND7mB_sgPQwgDQ",
    downloadUrl: "https://welib.st/md5/1b3f2e22c8810a6547fd91a1a580936c",
    format: "pdf",
    language: "Japanese",
    year: 1999,
    fileSize: "4.2 MB",
    category: "workbook",
    level: "N5",
    tags: ["Minna no Nihongo", "workbook", "exercises", "beginner"],
  },
  {
    id: "nihongo-notes-4",
    title: "Nihongo Notes 4: Understanding Communication in Japanese",
    originalTitle: "NIHONGO NOTES 4",
    author: "Osamu Mizutani & Nobuko Mizutani",
    description: "Tinjauan mendalam tentang budaya Jepang melalui 50 artikel Jepang/Inggris yang dipilih dari kolom 'Nihongo Notes' di The Japan Times.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2F2ada2b144c9b01ab522c7c7e0c5bb61e7e67dbb017714be1c854a55dc6410d10.jpg&md5=902565af51695471cf6ed351b3bfb856&key=tgI5Pv9VrICewhd7zfZ6MA",
    downloadUrl: "https://welib.st/md5/902565af51695471cf6ed351b3bfb856",
    format: "pdf",
    language: "English / Japanese",
    year: 1981,
    fileSize: "3.6 MB",
    category: "reading",
    level: "general",
    tags: ["culture", "communication", "reading", "Japan Times"],
  },
  {
    id: "nihongo-bunpo-nazo",
    title: "Nihongo Bunpo no Nazo o Toku",
    originalTitle: "日本語文法の謎を解く : 「ある」日本語と「する」英語",
    author: "金谷 武洋 (Kanaya Takehiro)",
    description: "Buku yang mengupas teka-teki tata bahasa Jepang dengan membandingkannya dengan bahasa Inggris. Cocok untuk pemahaman grammar tingkat menengah.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Farchive.org%2Fdownload%2Fisbn_9784480059833%2F__ia_thumb.jpg&md5=35ea26d0c94f4fb21003c1c7fdee2554&key=wd1DN-gVn0OSdjgNULpCVg",
    downloadUrl: "https://welib.st/md5/35ea26d0c94f4fb21003c1c7fdee2554",
    format: "pdf",
    language: "Japanese",
    year: 2003,
    fileSize: "5.9 MB",
    category: "grammar",
    level: "N3",
    tags: ["grammar", "linguistics", "intermediate", "academic"],
  },
  {
    id: "nihongo-now-l1v2",
    title: "NihonGO NOW! Level 1 Volume 2 Textbook",
    originalTitle: "日本語NOW! LEVEL 1 VOLUME 2 TEXTBOOK",
    author: "Mari Noda, Patricia Wetzel, et al.",
    description: "Paket kursus tingkat pemula dengan pendekatan performed-culture. Menyajikan bahasa dalam konteks budaya Jepang yang autentik dengan latihan berbasis performa.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fuserbooks%2F177ad5d371dd13e3d7940326a669782aff3472104ba05bc9b96d1dfafe5e60b6.jpg&md5=229cff8295cd1b566f5a437886769083&key=xFezsir-8svUqrRFgX7nDQ",
    downloadUrl: "https://welib.st/md5/229cff8295cd1b566f5a437886769083",
    format: "pdf",
    language: "English",
    year: 2020,
    fileSize: "10.4 MB",
    category: "textbook",
    level: "N5",
    tags: ["modern", "textbook", "culture", "beginner"],
  },
  {
    id: "nihongo-somotome-n2-vocab",
    title: "Nihongo So-matome N2: Vocabulary",
    originalTitle: "日本語総まとめ 問題集 新基準対応 2級 [語彙編]",
    author: "佐々木 仁子, 松本 紀子",
    description: "Buku latihan soal kosakata JLPT N2 yang terkenal. Mengikuti standar baru JLPT dengan materi terstruktur dan latihan lengkap.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2F480cd7ff21da3dbc469ce1187cca2c3305290ee873e2aaf96396b016053f7133.jpg&md5=24e4ad3a193e43380ec72bba1e50881c&key=_72rLJaRnT_D8q7XeXYf5w",
    downloadUrl: "https://welib.st/md5/24e4ad3a193e43380ec72bba1e50881c",
    format: "pdf",
    language: "Japanese",
    year: 2003,
    fileSize: "22.1 MB",
    category: "vocabulary",
    level: "N2",
    tags: ["So-matome", "vocabulary", "JLPT prep", "N2"],
  },
  {
    id: "try-n3-revised",
    title: "TRY! Japanese Language Proficiency Test N3 Revised Edition",
    originalTitle: "TRY! 日本語能力試験 N3",
    author: "Ajia Gakusei Bunka Kyokai",
    description: "Belajar 127 pola kalimat N3 melalui berbagai jenis teks: blog, pemberitahuan, resep, percakapan teman, dan wawancara. Dilengkapi ujian simulasi.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fuserbooks%2Fbee381caeb3f25bfa2ff9e7d5d591d16829bb37306c8fcd2db167fbabf03fa6f.jpg&md5=966cd636082dbff4817df7516f7f0954&key=7S_V8JWqsMEOgNnfyee6bg",
    downloadUrl: "https://welib.st/md5/966cd636082dbff4817df7516f7f0954",
    format: "pdf",
    language: "Japanese",
    year: 2014,
    fileSize: "69.5 MB",
    category: "workbook",
    level: "N3",
    tags: ["TRY!", "JLPT prep", "N3", "grammar", "reading", "listening"],
  },
  {
    id: "quartet-n2-workbook-2",
    title: "Quartet: Intermediate Japanese Vol. 2 Workbook",
    originalTitle: "QUARTET 中級日本語 2 ワークブック",
    author: "安井朱美, 井手友里子, et al.",
    description: "Workbook pendamping Quartet Vol. 2 untuk pembelajar menengah. Berisi latihan pemahaman bacaan, pola grammar, dan aktivitas kanji tingkat N2.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Flibgen.is%2Fcovers%2F4320000%2F13ca9b3e4af8e836d6374c68ba2e1e0c-g.jpg&md5=13ca9b3e4af8e836d6374c68ba2e1e0c&key=Wmuyg3zPjLLIolxo_y9x9A",
    downloadUrl: "https://welib.st/md5/13ca9b3e4af8e836d6374c68ba2e1e0c",
    format: "pdf",
    language: "Japanese",
    year: 2020,
    fileSize: "13.5 MB",
    category: "workbook",
    level: "N2",
    tags: ["Quartet", "intermediate", "N2", "workbook", "reading", "kanji"],
  },
  {
    id: "nihongo-no-kiso-2-translation",
    title: "Nihongo No Kiso II: English Translation",
    originalTitle: "日本語の基礎 II 英訳",
    author: "Kaigai Gijutsusha Kenshu Kyokai",
    description: "Seri Nihongo no Kiso yang klasik. Buku terjemahan bahasa Inggris untuk volume 2, cocok untuk pembelajar yang ingin memahami teks asli Jepang.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Farchive.org%2Fdownload%2Fnihongonokisoii0000unse%2F__ia_thumb.jpg&md5=2a7bef619ccab2bd72b225fa4cd24fb6&key=lxz77Dm_iA8B8tcPAbMPjQ",
    downloadUrl: "https://welib.st/md5/2a7bef619ccab2bd72b225fa4cd24fb6",
    format: "pdf",
    language: "Japanese",
    year: 1973,
    fileSize: "6.7 MB",
    category: "textbook",
    level: "N5",
    tags: ["classic", "textbook", "beginner", "Nihongo no Kiso"],
  },
  {
    id: "genki-1-textbook",
    title: "Genki: An Integrated Course in Elementary Japanese I",
    originalTitle: "GENKI I: 初級日本語",
    author: "Eri Banno, Yoko Ikuta, et al.",
    description: "Buku teks Jepang terpopuler di universitas. Menggabungkan speaking, listening, reading, dan writing dalam satu kurikulum terpadu untuk pemula.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fgenki1.jpg&md5=genki1placeholder&key=genki1",
    downloadUrl: "https://welib.st/search?q=genki+integrated+elementary+japanese",
    format: "pdf",
    language: "English / Japanese",
    year: 2011,
    fileSize: "~35 MB",
    category: "textbook",
    level: "N5",
    tags: ["Genki", "popular", "textbook", "university", "beginner"],
  },
  {
    id: "genki-2-textbook",
    title: "Genki: An Integrated Course in Elementary Japanese II",
    originalTitle: "GENKI II: 初級日本語",
    author: "Eri Banno, Yoko Ikuta, et al.",
    description: "Lanjutan dari Genki I. Memperluas kosakata dan tata bahasa hingga level N4. Tetap menjadi buku teks universitas pilihan di seluruh dunia.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fgenki2.jpg&md5=genki2placeholder&key=genki2",
    downloadUrl: "https://welib.st/search?q=genki+2+integrated+elementary+japanese",
    format: "pdf",
    language: "English / Japanese",
    year: 2011,
    fileSize: "~38 MB",
    category: "textbook",
    level: "N4",
    tags: ["Genki", "popular", "textbook", "university", "intermediate"],
  },
  {
    id: "dictionary-of-basic-japanese-grammar",
    title: "A Dictionary of Basic Japanese Grammar",
    originalTitle: "A Dictionary of Basic Japanese Grammar",
    author: "Seiichi Makino & Michio Tsutsui",
    description: "Kamus tata bahasa Jepang dasar yang komprehensif. Penjelasan mendalam untuk setiap pola kalimat dengan contoh autentik dan perbandingan usage.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fdictionary_basic.jpg&md5=dictbasic&key=dictbasic",
    downloadUrl: "https://welib.st/search?q=dictionary+of+basic+japanese+grammar",
    format: "pdf",
    language: "English",
    year: 1986,
    fileSize: "~18 MB",
    category: "dictionary",
    level: "N5",
    tags: ["dictionary", "grammar", "reference", "classic", "Makino"],
  },
  {
    id: "dictionary-of-intermediate-japanese-grammar",
    title: "A Dictionary of Intermediate Japanese Grammar",
    originalTitle: "A Dictionary of Intermediate Japanese Grammar",
    author: "Seiichi Makino & Michio Tsutsui",
    description: "Kamus tata bahasa Jepang menengah. Membahas nuansa dan penggunaan grammar tingkat N3–N2 dengan contoh kalimat yang kaya dan perbandingan yang jelas.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fdictionary_intermediate.jpg&md5=dictinter&key=dictinter",
    downloadUrl: "https://welib.st/search?q=dictionary+of+intermediate+japanese+grammar",
    format: "pdf",
    language: "English",
    year: 1995,
    fileSize: "~22 MB",
    category: "dictionary",
    level: "N3",
    tags: ["dictionary", "grammar", "reference", "Makino", "intermediate"],
  },
  {
    id: "dictionary-of-advanced-japanese-grammar",
    title: "A Dictionary of Advanced Japanese Grammar",
    originalTitle: "A Dictionary of Advanced Japanese Grammar",
    author: "Seiichi Makino & Michio Tsutsui",
    description: "Kamus tata bahasa Jepang tingkat lanjut (N2–N1). Membahas pola-pola kalimat kompleks, nuansa formal, dan ekspresi tingkat tinggi dalam bahasa Jepang.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fdictionary_advanced.jpg&md5=dictadv&key=dictadv",
    downloadUrl: "https://welib.st/search?q=dictionary+of+advanced+japanese+grammar",
    format: "pdf",
    language: "English",
    year: 2008,
    fileSize: "~28 MB",
    category: "dictionary",
    level: "N1",
    tags: ["dictionary", "grammar", "reference", "advanced", "Makino"],
  },
  {
    id: "shadowing-japanese",
    title: "Shadowing Japanese: Let's Speak Japanese!",
    originalTitle: "Shadowing 日本語",
    author: "Katsuyoshi Tsutsui",
    description: "Metode shadowing untuk melatih speaking dan listening. Dengarkan audio dan ikuti pengucapan dalam waktu yang hampir bersamaan. Sangat efektif untuk fluency.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fshadowing.jpg&md5=shadow&key=shadow",
    downloadUrl: "https://welib.st/search?q=shadowing+japanese+speak",
    format: "pdf",
    language: "Japanese / English",
    year: 2012,
    fileSize: "~12 MB",
    category: "textbook",
    level: "N4",
    tags: ["shadowing", "speaking", "listening", "fluency", "pronunciation"],
  },
  {
    id: "kanji-dictionary",
    title: "The Kodansha Kanji Learner's Dictionary",
    originalTitle: "Kodansha Kanji Learner's Dictionary",
    author: "Jack Halpern",
    description: "Kamus kanji terbaik untuk pembelajar asing. Sistem SKIP inovatif memudahkan pencarian kanji berdasarkan bentuk visual, bukan radical saja.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fkanji_dict.jpg&md5=kanjidict&key=kanjidict",
    downloadUrl: "https://welib.st/search?q=kodansha+kanji+learner+dictionary",
    format: "pdf",
    language: "English",
    year: 2013,
    fileSize: "~45 MB",
    category: "dictionary",
    level: "general",
    tags: ["kanji", "dictionary", "reference", "SKIP", "Kodansha"],
  },
  {
    id: "remembering-the-kanji-1",
    title: "Remembering the Kanji 1",
    originalTitle: "Remembering the Kanji 1",
    author: "James W. Heisig",
    description: "Metode mnemonik untuk mengingat 2.042 kanji Joyo. Setiap kanji diberi cerita kata kunci yang menghubungkan komponen dengan makna, tanpa perlu menghafal urutan stroke.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Frtk1.jpg&md5=rtk1&key=rtk1",
    downloadUrl: "https://welib.st/search?q=remembering+the+kanji+heisig",
    format: "pdf",
    language: "English",
    year: 2012,
    fileSize: "~15 MB",
    category: "dictionary",
    level: "general",
    tags: ["kanji", "Heisig", "RTK", "mnemonics", "memorization"],
  },
  {
    id: "remembering-the-kanji-2",
    title: "Remembering the Kanji 2",
    originalTitle: "Remembering the Kanji 2",
    author: "James W. Heisig",
    description: "Lanjutan RTK 1 yang fokus pada readings (onyomi dan kunyomi). Menggunakan sistem 'frame' untuk mengaitkan kanji dengan pelafalan melalui cerita mnemonik.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Frtk2.jpg&md5=rtk2&key=rtk2",
    downloadUrl: "https://welib.st/search?q=remembering+the+kanji+2+heisig",
    format: "pdf",
    language: "English",
    year: 2012,
    fileSize: "~12 MB",
    category: "dictionary",
    level: "general",
    tags: ["kanji", "Heisig", "RTK", "readings", "onyomi", "kunyomi"],
  },
  {
    id: "shinkansen-n4-grammar",
    title: "Shinkansen Master N4: Grammar",
    originalTitle: "新完全マスター N4 文法",
    author: "Tomomatsu Etsuko",
    description: "Buku persiapan JLPT N4 yang terkenal. Penjelasan grammar yang sistematis dengan banyak latihan soal sesuai format ujian JLPT yang sebenarnya.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fshinkanzen_n4.jpg&md5=skn4&key=skn4",
    downloadUrl: "https://welib.st/search?q=shinkanzen+master+N4+grammar",
    format: "pdf",
    language: "Japanese / English",
    year: 2012,
    fileSize: "~20 MB",
    category: "workbook",
    level: "N4",
    tags: ["Shinkanzen Master", "JLPT prep", "N4", "grammar", "workbook"],
  },
  {
    id: "shinkansen-n3-grammar",
    title: "Shinkansen Master N3: Grammar",
    originalTitle: "新完全マスター N3 文法",
    author: "Tomomatsu Etsuko",
    description: "Master grammar JLPT N3 dengan pendekatan 'sistematis dan menyeluruh'. Setiap unit memiliki penjelasan mendalam, contoh, dan latihan berjenjang.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fshinkanzen_n3.jpg&md5=skn3&key=skn3",
    downloadUrl: "https://welib.st/search?q=shinkanzen+master+N3+grammar",
    format: "pdf",
    language: "Japanese / English",
    year: 2012,
    fileSize: "~25 MB",
    category: "workbook",
    level: "N3",
    tags: ["Shinkanzen Master", "JLPT prep", "N3", "grammar", "workbook"],
  },
  {
    id: "shinkansen-n2-grammar",
    title: "Shinkansen Master N2: Grammar",
    originalTitle: "新完全マスター N2 文法",
    author: "Tomomatsu Etsuko",
    description: "Buku grammar N2 yang paling direkomendasikan. Menyeluruh, sistematis, dan langsung relevan dengan soal-soal JLPT N2 yang sesungguhnya.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fshinkanzen_n2.jpg&md5=skn2&key=skn2",
    downloadUrl: "https://welib.st/search?q=shinkanzen+master+N2+grammar",
    format: "pdf",
    language: "Japanese / English",
    year: 2013,
    fileSize: "~28 MB",
    category: "workbook",
    level: "N2",
    tags: ["Shinkanzen Master", "JLPT prep", "N2", "grammar", "workbook"],
  },
  {
    id: "shinkansen-n1-grammar",
    title: "Shinkansen Master N1: Grammar",
    originalTitle: "新完全マスター N1 文法",
    author: "Tomomatsu Etsuko",
    description: "Grammar JLPT N1 tingkat mahir. Membahas nuansa halus, ekspresi formal, dan pola kalimat kompleks yang sering muncul di ujian level tertinggi.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fshinkanzen_n1.jpg&md5=skn1&key=skn1",
    downloadUrl: "https://welib.st/search?q=shinkanzen+master+N1+grammar",
    format: "pdf",
    language: "Japanese / English",
    year: 2013,
    fileSize: "~30 MB",
    category: "workbook",
    level: "N1",
    tags: ["Shinkanzen Master", "JLPT prep", "N1", "grammar", "workbook"],
  },
  {
    id: "jlpt-n5-official-workbook",
    title: "JLPT N5 Official Practice Workbook",
    originalTitle: "日本語能力試験 N5 公式問題集",
    author: "Japan Foundation / JEES",
    description: "Buku latihan soal resmi dari penyelenggara JLPT. Berisi soal-soal asli dari ujian tahun-tahun sebelumnya dengan kunci jawaban dan penjelasan lengkap.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fn5_official.jpg&md5=n5off&key=n5off",
    downloadUrl: "https://welib.st/search?q=JLPT+N5+official+practice+workbook",
    format: "pdf",
    language: "Japanese",
    year: 2018,
    fileSize: "~8 MB",
    category: "workbook",
    level: "N5",
    tags: ["official", "JLPT prep", "N5", "practice test", "past papers"],
  },
  {
    id: "jlpt-n4-official-workbook",
    title: "JLPT N4 Official Practice Workbook",
    originalTitle: "日本語能力試験 N4 公式問題集",
    author: "Japan Foundation / JEES",
    description: "Soal-soal latihan resmi JLPT N4 dari Japan Foundation. Format persis seperti ujian sesungguhnya dengan CD audio untuk bagian listening.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fn4_official.jpg&md5=n4off&key=n4off",
    downloadUrl: "https://welib.st/search?q=JLPT+N4+official+practice+workbook",
    format: "pdf",
    language: "Japanese",
    year: 2018,
    fileSize: "~9 MB",
    category: "workbook",
    level: "N4",
    tags: ["official", "JLPT prep", "N4", "practice test", "past papers"],
  },
  {
    id: "jlpt-n3-official-workbook",
    title: "JLPT N3 Official Practice Workbook",
    originalTitle: "日本語能力試験 N3 公式問題集",
    author: "Japan Foundation / JEES",
    description: "Kumpulan soal resmi JLPT N3. Merupakan sumber terpercaya untuk memahami format dan tingkat kesulitan ujian JLPT level menengah.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fn3_official.jpg&md5=n3off&key=n3off",
    downloadUrl: "https://welib.st/search?q=JLPT+N3+official+practice+workbook",
    format: "pdf",
    language: "Japanese",
    year: 2018,
    fileSize: "~12 MB",
    category: "workbook",
    level: "N3",
    tags: ["official", "JLPT prep", "N3", "practice test", "past papers"],
  },
  {
    id: "501-japanese-verbs",
    title: "501 Japanese Verbs",
    originalTitle: "501 Japanese Verbs",
    author: "R. L. Altus & R. A. Lange",
    description: "Referensi lengkap 501 kata kerja Jepang paling penting dengan konjugasi lengkap untuk setiap bentuk: masu, te, ta, nai, potential, passive, causative, dan conditional.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2F501verbs.jpg&md5=501v&key=501v",
    downloadUrl: "https://welib.st/search?q=501+japanese+verbs+barron",
    format: "pdf",
    language: "English",
    year: 2003,
    fileSize: "~6 MB",
    category: "dictionary",
    level: "N5",
    tags: ["verbs", "conjugation", "reference", "dictionary", "beginner"],
  },
  {
    id: "essential-japanese-vocabulary",
    title: "Essential Japanese Vocabulary",
    originalTitle: "必須日本語単語集",
    author: "Akira Miura",
    description: "Kumpulan kosakata esensial Jepang yang dikelompokkan berdasarkan tema dan frekuensi penggunaan. Dilengkapi contoh kalimat dan catatan penggunaan.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fessential_vocab.jpg&md5=evocab&key=evocab",
    downloadUrl: "https://welib.st/search?q=essential+japanese+vocabulary+miura",
    format: "pdf",
    language: "English / Japanese",
    year: 2011,
    fileSize: "~8 MB",
    category: "vocabulary",
    level: "N4",
    tags: ["vocabulary", "thematic", "frequency", "beginner", "reference"],
  },
  {
    id: "breaking-into-japanese-literature",
    title: "Breaking into Japanese Literature",
    originalTitle: "Breaking into Japanese Literature",
    author: "Giles Murray",
    description: "Buku bacaan sastra Jepang untuk pembelajar menengah. Tujuh karya klasik Jepang disajikan dengan furigana, terjemahan per kalimat, dan catatan budaya.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fbreaking_lit.jpg&md5=breaklit&key=breaklit",
    downloadUrl: "https://welib.st/search?q=breaking+into+japanese+literature+giles+murray",
    format: "pdf",
    language: "Japanese / English",
    year: 2003,
    fileSize: "~10 MB",
    category: "reading",
    level: "N3",
    tags: ["literature", "reading", "culture", "intermediate", "furigana"],
  },
  {
    id: "read-real-japanese",
    title: "Read Real Japanese: Essays",
    originalTitle: "Read Real Japanese Essays",
    author: "Janet Ashby",
    description: "Esai-esai Jepang asli yang disunting untuk pembelajar. Setiap esai dilengkapi dengan terjemahan, catatan kosakata, dan penjelasan tata bahasa di samping teks.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fread_real_jp.jpg&md5=rrj&key=rrj",
    downloadUrl: "https://welib.st/search?q=read+real+japanese+essays",
    format: "pdf",
    language: "Japanese / English",
    year: 2012,
    fileSize: "~11 MB",
    category: "reading",
    level: "N3",
    tags: ["reading", "essays", "authentic", "intermediate", "culture"],
  },
  {
    id: "japanese-the-spoken-language-1",
    title: "Japanese: The Spoken Language Part 1",
    originalTitle: "Japanese: The Spoken Language",
    author: "Eleanor Harz Jorden",
    description: "Kursus bahasa lisan Jepang klasik dari Universitas Yale. Fokus pada pengucapan, intonasi, dan pola percakapan yang sering digunakan dalam kehidupan nyata.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fjsl1.jpg&md5=jsl1&key=jsl1",
    downloadUrl: "https://welib.st/search?q=japanese+the+spoken+language+jorden",
    format: "pdf",
    language: "English",
    year: 1987,
    fileSize: "~14 MB",
    category: "textbook",
    level: "N5",
    tags: ["speaking", "listening", "pronunciation", "classic", "Yale"],
  },
  {
    id: "integrated-approach-intermediate-japanese",
    title: "An Integrated Approach to Intermediate Japanese",
    originalTitle: "中級への日本語",
    author: "Miura & McGloin",
    description: "Buku teks menengah yang terintegrasi. Menggabungkan reading, writing, listening, dan speaking dengan teks autentik dari media Jepang.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fintermediate_jp.jpg&md5=intjp&key=intjp",
    downloadUrl: "https://welib.st/search?q=integrated+approach+intermediate+japanese",
    format: "pdf",
    language: "Japanese / English",
    year: 2008,
    fileSize: "~20 MB",
    category: "textbook",
    level: "N3",
    tags: ["intermediate", "textbook", "integrated", "reading", "media"],
  },
  {
    id: "tobira-gateway-advanced-japanese",
    title: "Tobira: Gateway to Advanced Japanese",
    originalTitle: "とびら: 中級から上級への日本語",
    author: "Mayumi Oka, et al.",
    description: "Buku teks untuk transisi dari menengah ke lanjut. Membahas topik akademik dan sosial Jepang dengan teks panjang dan grammar tingkat N2–N1.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Ftobira.jpg&md5=tobira&key=tobira",
    downloadUrl: "https://welib.st/search?q=tobira+gateway+advanced+japanese",
    format: "pdf",
    language: "Japanese / English",
    year: 2009,
    fileSize: "~32 MB",
    category: "textbook",
    level: "N2",
    tags: ["Tobira", "advanced", "textbook", "academic", "N2", "transition"],
  },
  {
    id: "authentic-japanese-progressing-from-intermediate-to-advanced",
    title: "Authentic Japanese: Progressing from Intermediate to Advanced",
    originalTitle: "本物の日本語",
    author: "Sumiko Yotsuya & Nobuo Akiyama",
    description: "Bahan bacaan autentik untuk meningkatkan kemampuan dari N3 ke N2. Artikel dari koran, majalah, dan esai Jepang asli dengan catatan mendalam.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fauthentic_jp.jpg&md5=authjp&key=authjp",
    downloadUrl: "https://welib.st/search?q=authentic+japanese+intermediate+advanced",
    format: "pdf",
    language: "Japanese / English",
    year: 2003,
    fileSize: "~15 MB",
    category: "reading",
    level: "N2",
    tags: ["authentic", "reading", "intermediate", "advanced", "newspaper", "N2"],
  },
  {
    id: "kanji-in-context",
    title: "Kanji in Context",
    originalTitle: "漢字学習ステップ",
    author: "Nishiguchi & Kono",
    description: "Belajar kanji melalui konteks kalimat nyata. Setiap kanji dipresentasikan dalam berbagai kombinasi dan contoh penggunaan, bukan hanya arti terjemahan.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fkanji_context.jpg&md5=kicontext&key=kicontext",
    downloadUrl: "https://welib.st/search?q=kanji+in+context+reference",
    format: "pdf",
    language: "Japanese / English",
    year: 2007,
    fileSize: "~18 MB",
    category: "vocabulary",
    level: "N3",
    tags: ["kanji", "context", "vocabulary", "intermediate", "combinations"],
  },
  {
    id: "a-guide-to-japanese-grammar",
    title: "A Guide to Japanese Grammar",
    originalTitle: "日本語文法ガイド",
    author: "Tae Kim",
    description: "Panduan grammar Jepang gratis yang menjadi legenda di internet. Penjelasan dari sudut pandang bahasa Jepang asli, bukan terjemahan bahasa Inggris.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Ftaekim.jpg&md5=taekim&key=taekim",
    downloadUrl: "https://welib.st/search?q=tae+kim+guide+japanese+grammar",
    format: "pdf",
    language: "English",
    year: 2014,
    fileSize: "~5 MB",
    category: "grammar",
    level: "N5",
    tags: ["Tae Kim", "free", "grammar", "beginner", "classic", "internet"],
  },
  {
    id: "making-sense-of-japanese",
    title: "Making Sense of Japanese: What the Textbooks Don't Tell You",
    originalTitle: "Making Sense of Japanese",
    author: "Jay Rubin",
    description: "Buku yang menjelaskan nuansa grammar Jepang yang sering tidak tercakup di buku teks. Membahas particles, keigo, dan ekspresi dengan humor dan kejelasan.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fmaking_sense.jpg&md5=makesense&key=makesense",
    downloadUrl: "https://welib.st/search?q=making+sense+of+japanese+jay+rubin",
    format: "pdf",
    language: "English",
    year: 2002,
    fileSize: "~7 MB",
    category: "grammar",
    level: "N3",
    tags: ["grammar", "nuance", "intermediate", "particles", "Jay Rubin"],
  },
  {
    id: "japanese-sentence-patterns-for-effective-communication",
    title: "Japanese Sentence Patterns for Effective Communication",
    originalTitle: "日本語文型辞典",
    author: "Toshiko Yamane",
    description: "Kumpulan pola kalimat Jepang yang paling sering digunakan dalam komunikasi sehari-hari. Setiap pola dilengkapi dengan situasi penggunaan dan variasi.",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fsentence_patterns.jpg&md5=spattern&key=spattern",
    downloadUrl: "https://welib.st/search?q=japanese+sentence+patterns+effective+communication",
    format: "pdf",
    language: "English / Japanese",
    year: 2003,
    fileSize: "~9 MB",
    category: "grammar",
    level: "N4",
    tags: ["patterns", "communication", "practical", "beginner", "intermediate"],
  },
  {
    id: "core-6000-japanese-words",
    title: "Core 6000 Japanese Words",
    originalTitle: "日本語核心単語6000",
    author: "Shin Nihongo",
    description: "6000 kosakata Jepang paling penting yang diurutkan berdasarkan frekuensi. Dilengkapi contoh kalimat, kolokasi, dan informasi register (formal/informal).",
    coverUrl: "https://s2.welib-public.org/covers/proxy?url=https%3A%2F%2Fs3proxy.cdn-zlib.sk%2F%2Fcovers299%2Fcollections%2Fgenesis%2Fcore6000.jpg&md5=core6k&key=core6k",
    downloadUrl: "https://welib.st/search?q=core+6000+japanese+words+iwako",
    format: "pdf",
    language: "Japanese / English",
    year: 2010,
    fileSize: "~16 MB",
    category: "vocabulary",
    level: "general",
    tags: ["vocabulary", "frequency", "core", "comprehensive", "reference"],
  },
];

export const ebookCategories = [
  { value: "all", label: "Semua" },
  { value: "textbook", label: "Buku Teks" },
  { value: "grammar", label: "Tata Bahasa" },
  { value: "vocabulary", label: "Kosakata" },
  { value: "reading", label: "Bacaan" },
  { value: "workbook", label: "Buku Latihan" },
  { value: "dictionary", label: "Kamus & Referensi" },
  { value: "other", label: "Lainnya" },
] as const;

export const ebookLevels = [
  { value: "all", label: "Semua Level" },
  { value: "N5", label: "N5 — Pemula" },
  { value: "N4", label: "N4 — Dasar" },
  { value: "N3", label: "N3 — Menengah" },
  { value: "N2", label: "N2 — Mahir" },
  { value: "N1", label: "N1 — Ahli" },
  { value: "general", label: "Umum" },
] as const;
