import type { LevelContent } from "./types";

export const n1: LevelContent = {
  level: "N1",
  title: "JLPT N1 — Ahli",
  tagline: "Tingkat tertinggi — kefasihan setara native",
  description: "Pahami bahasa Jepang dalam segala konteks: akademis, sastra, hukum, dan abstrak.",
  hours: "900+ jam",
  kanjiCount: 2000,
  vocabCount: 10000,
  grammarCount: 250,
  kanji: [
    { kanji: "曖", on: "アイ", kun: "—", meaning: "samar", example: "曖昧 (aimai)" },
    { kanji: "昧", on: "マイ", kun: "—", meaning: "gelap", example: "曖昧 (aimai)" },
    { kanji: "憂", on: "ユウ", kun: "うれ", meaning: "khawatir", example: "憂鬱 (yūutsu)" },
    { kanji: "鬱", on: "ウツ", kun: "—", meaning: "muram", example: "憂鬱 (yūutsu)" },
    { kanji: "錯", on: "サク", kun: "—", meaning: "bercampur", example: "錯覚 (sakkaku)" },
    { kanji: "顕", on: "ケン", kun: "あらわ", meaning: "nyata", example: "顕著 (kencho)" },
    { kanji: "著", on: "チョ", kun: "あらわ", meaning: "menulis", example: "著者 (chosha)" },
    { kanji: "暫", on: "ザン", kun: "しばら", meaning: "sementara", example: "暫定 (zantei)" },
    { kanji: "謀", on: "ボウ", kun: "はか", meaning: "konspirasi", example: "陰謀 (inbō)" },
    { kanji: "陰", on: "イン", kun: "かげ", meaning: "bayangan", example: "陰謀 (inbō)" },
    { kanji: "葛", on: "カツ", kun: "くず", meaning: "tumbuhan merambat", example: "葛藤 (kattō)" },
    { kanji: "藤", on: "トウ", kun: "ふじ", meaning: "wisteria", example: "葛藤 (kattō)" },
    { kanji: "凌", on: "リョウ", kun: "しの", meaning: "melampaui", example: "凌駕 (ryōga)" },
    { kanji: "駕", on: "ガ", kun: "—", meaning: "kereta", example: "凌駕 (ryōga)" },
    { kanji: "踏", on: "トウ", kun: "ふ", meaning: "menginjak", example: "踏襲 (tōshū)" },
    { kanji: "襲", on: "シュウ", kun: "おそ", meaning: "menyerang", example: "踏襲 (tōshū)" },
    { kanji: "陶", on: "トウ", kun: "—", meaning: "keramik", example: "陶冶 (tōya)" },
    { kanji: "冶", on: "ヤ", kun: "—", meaning: "metalurgi", example: "陶冶 (tōya)" },
    { kanji: "穏", on: "オン", kun: "おだ", meaning: "tenang", example: "穏健 (onken)" },
    { kanji: "嫌", on: "ケン", kun: "きら", meaning: "tidak suka", example: "嫌悪 (ken'o)" },
    { kanji: "悪", on: "アク", kun: "わる", meaning: "jahat", example: "悪化 (akka)" },
    { kanji: "謙", on: "ケン", kun: "へりくだ", meaning: "rendah hati", example: "謙虚 (kenkyo)" },
    { kanji: "虚", on: "キョ", kun: "むな", meaning: "kosong", example: "虚偽 (kyogi)" },
    { kanji: "偽", on: "ギ", kun: "にせ", meaning: "palsu", example: "偽装 (gisō)" },
    { kanji: "潜", on: "セン", kun: "ひそ", meaning: "tersembunyi", example: "潜在 (senzai)" },
  ],
  vocabulary: [
    { jp: "曖昧", romaji: "aimai", meaning: "ambigu", category: "Sifat" },
    { jp: "顕著", romaji: "kencho", meaning: "menonjol", category: "Sifat" },
    { jp: "暫定", romaji: "zantei", meaning: "sementara", category: "Sifat" },
    { jp: "穏健", romaji: "onken", meaning: "moderat", category: "Sifat" },
    { jp: "謙虚", romaji: "kenkyo", meaning: "rendah hati", category: "Sifat" },
    { jp: "錯覚", romaji: "sakkaku", meaning: "ilusi", category: "Abstrak" },
    { jp: "憂鬱", romaji: "yūutsu", meaning: "depresi", category: "Emosi" },
    { jp: "葛藤", romaji: "kattō", meaning: "konflik batin", category: "Emosi" },
    { jp: "嫌悪", romaji: "ken'o", meaning: "kebencian", category: "Emosi" },
    { jp: "覆す", romaji: "kutsugaesu", meaning: "membalikkan", category: "Kata kerja" },
    { jp: "凌駕", romaji: "ryōga", meaning: "melampaui", category: "Kata kerja" },
    { jp: "踏襲", romaji: "tōshū", meaning: "mengikuti tradisi", category: "Kata kerja" },
    { jp: "陶冶", romaji: "tōya", meaning: "mendidik", category: "Kata kerja" },
    { jp: "潜む", romaji: "hisomu", meaning: "tersembunyi", category: "Kata kerja" },
    { jp: "偽る", romaji: "itsuwaru", meaning: "berbohong", category: "Kata kerja" },
    { jp: "貫く", romaji: "tsuranuku", meaning: "mempertahankan", category: "Kata kerja" },
    { jp: "委ねる", romaji: "yudaneru", meaning: "mempercayakan", category: "Kata kerja" },
    { jp: "賄う", romaji: "makanau", meaning: "menyediakan", category: "Kata kerja" },
    { jp: "募る", romaji: "tsunoru", meaning: "merekrut/meningkat", category: "Kata kerja" },
    { jp: "免れる", romaji: "manukareru", meaning: "lolos dari", category: "Kata kerja" },
    { jp: "陰謀", romaji: "inbō", meaning: "konspirasi", category: "Abstrak" },
    { jp: "潜在", romaji: "senzai", meaning: "potensial/laten", category: "Abstrak" },
    { jp: "虚偽", romaji: "kyogi", meaning: "kepalsuan", category: "Abstrak" },
    { jp: "偽装", romaji: "gisō", meaning: "penyamaran", category: "Abstrak" },
    { jp: "本質", romaji: "honshitsu", meaning: "esensi", category: "Abstrak" },
    { jp: "矛先", romaji: "hokosaki", meaning: "arah serangan", category: "Abstrak" },
    { jp: "形跡", romaji: "keiseki", meaning: "jejak", category: "Abstrak" },
    { jp: "兆候", romaji: "chōkō", meaning: "tanda awal", category: "Abstrak" },
    { jp: "余地", romaji: "yochi", meaning: "ruang/kesempatan", category: "Abstrak" },
    { jp: "趣旨", romaji: "shushi", meaning: "maksud, esensi", category: "Abstrak" },
  ],
  grammar: [
    { pattern: "〜を余儀なくされる", meaning: "Terpaksa ~", example: "中止を余儀なくされた。", exampleMeaning: "Terpaksa dibatalkan." },
    { pattern: "〜にかたくない", meaning: "Tidak sulit untuk ~", example: "想像にかたくない。", exampleMeaning: "Mudah dibayangkan." },
    { pattern: "〜ともなると", meaning: "Kalau sudah ~", example: "社長ともなると忙しい。", exampleMeaning: "Kalau sudah jadi direktur, sibuk." },
    { pattern: "〜きらいがある", meaning: "Cenderung ~", example: "怠けるきらいがある。", exampleMeaning: "Cenderung malas." },
    { pattern: "〜と相まって", meaning: "Bersamaan dengan ~", example: "努力と相まって成功した。", exampleMeaning: "Berhasil bersamaan dengan usaha." },
    { pattern: "〜にして", meaning: "Pada usia/tingkat ~", example: "80歳にして現役。", exampleMeaning: "Pada usia 80 masih aktif." },
    { pattern: "〜なくして", meaning: "Tanpa ~", example: "努力なくして成功はない。", exampleMeaning: "Tanpa usaha, tak ada sukses." },
    { pattern: "〜であれ", meaning: "Apapun ~", example: "誰であれ平等だ。", exampleMeaning: "Siapapun setara." },
    { pattern: "〜まじき", meaning: "Tidak pantas ~", example: "あるまじき行為だ。", exampleMeaning: "Tindakan yang tidak pantas." },
    { pattern: "〜ながらに", meaning: "Sambil/sejak ~", example: "生まれながらに才能がある。", exampleMeaning: "Berbakat sejak lahir." },
    { pattern: "〜が早いか", meaning: "Begitu ~ langsung ~", example: "見るが早いか走り出した。", exampleMeaning: "Begitu melihat, langsung berlari." },
    { pattern: "〜や否や", meaning: "Tepat saat ~", example: "着くや否や倒れた。", exampleMeaning: "Begitu sampai, langsung jatuh." },
    { pattern: "〜ばこそ", meaning: "Justru karena ~", example: "愛していればこそ厳しい。", exampleMeaning: "Justru karena cinta, dia tegas." },
    { pattern: "〜とあって", meaning: "Karena ~ (alasan)", example: "祭りとあって賑やかだ。", exampleMeaning: "Ramai karena festival." },
    { pattern: "〜ともあろう", meaning: "Untuk seseorang seperti ~", example: "プロともあろう人が。", exampleMeaning: "Untuk seorang profesional sekelas dia." },
    { pattern: "〜にあって", meaning: "Pada situasi ~", example: "この時代にあって。", exampleMeaning: "Pada zaman ini." },
    { pattern: "〜の至り", meaning: "Sangat ~", example: "光栄の至りです。", exampleMeaning: "Suatu kehormatan besar." },
    { pattern: "〜の極み", meaning: "Puncak ~", example: "贅沢の極み。", exampleMeaning: "Kemewahan yang puncak." },
    { pattern: "〜限りだ", meaning: "Sangat ~", example: "嬉しい限りだ。", exampleMeaning: "Sangat senang." },
    { pattern: "〜を禁じ得ない", meaning: "Tak dapat menahan ~", example: "怒りを禁じ得ない。", exampleMeaning: "Tak bisa menahan amarah." },
  ],
  sentences: [
    { jp: "彼の発言は曖昧で趣旨がつかめない。", romaji: "kare no hatsugen wa aimai de shushi ga tsukamenai.", meaning: "Pernyataannya ambigu sehingga maksudnya sulit ditangkap." },
    { jp: "事態は深刻化の一途を辿っている。", romaji: "jitai wa shinkokuka no itto o tadotte iru.", meaning: "Situasi terus memburuk." },
    { jp: "努力なくして成功はあり得ない。", romaji: "doryoku nakushite seikō wa arienai.", meaning: "Tanpa usaha, sukses mustahil." },
    { jp: "プロともあろう者がそんなミスをするとは。", romaji: "puro to mo arō mono ga sonna misu o suru to wa.", meaning: "Mengejutkan seorang profesional bisa membuat kesalahan begitu." },
    { jp: "若くしてこれほどの成果を上げるとは見事だ。", romaji: "wakaku shite kore hodo no seika o ageru to wa migoto da.", meaning: "Mencapai prestasi sebesar ini di usia muda sungguh luar biasa." },
    { jp: "彼の活躍は称賛に値する。", romaji: "kare no katsuyaku wa shōsan ni atai suru.", meaning: "Kiprahnya layak dipuji." },
    { jp: "状況が状況だけに慎重にならざるを得ない。", romaji: "jōkyō ga jōkyō dake ni shinchō ni narazaru o enai.", meaning: "Karena situasinya begini, kami harus hati-hati." },
    { jp: "怒りを禁じ得ない出来事だった。", romaji: "ikari o kinjienai dekigoto datta.", meaning: "Sebuah kejadian yang membuat amarah tak tertahan." },
    { jp: "彼の謙虚な態度には頭が下がる。", romaji: "kare no kenkyo na taido ni wa atama ga sagaru.", meaning: "Saya tunduk pada sikap rendah hatinya." },
    { jp: "問題の本質を見極める必要がある。", romaji: "mondai no honshitsu o mikiwameru hitsuyō ga aru.", meaning: "Esensi masalah perlu dipahami sepenuhnya." },
    { jp: "改革なくしてこの組織に未来はない。", romaji: "kaikaku nakushite kono soshiki ni mirai wa nai.", meaning: "Tanpa reformasi, organisasi ini tak punya masa depan." },
    { jp: "彼女は生まれながらにして才能に恵まれている。", romaji: "kanojo wa umarenagara ni shite sainō ni megumarete iru.", meaning: "Dia diberkahi bakat sejak lahir." },
    { jp: "この決定は社会に多大な影響を及ぼすだろう。", romaji: "kono kettei wa shakai ni tadai na eikyō o oyobosu darō.", meaning: "Keputusan ini akan berdampak besar pada masyarakat." },
    { jp: "予想だにしなかった結末を迎えた。", romaji: "yosō dani shinakatta ketsumatsu o mukaeta.", meaning: "Berakhir dengan cara yang sama sekali tak diduga." },
    { jp: "彼の業績は他の追随を許さない。", romaji: "kare no gyōseki wa ta no tsuizui o yurusanai.", meaning: "Prestasinya tak tertandingi oleh siapa pun." },
  ],
};
