import type { LevelContent } from "./types";

export const n2: LevelContent = {
  level: "N2",
  title: "JLPT N2 — Mahir",
  tagline: "Kuasai bahasa Jepang dalam konteks luas",
  description: "Pahami koran, berita, drama, dan komunikasi profesional dengan lancar.",
  hours: "600 jam",
  kanjiCount: 1000,
  vocabCount: 6000,
  grammarCount: 200,
  kanji: [
    { kanji: "概", on: "ガイ", kun: "—", meaning: "umum", example: "概念 (gainen)" },
    { kanji: "念", on: "ネン", kun: "—", meaning: "pikiran", example: "理念 (rinen)" },
    { kanji: "傾", on: "ケイ", kun: "かたむ", meaning: "miring", example: "傾向 (keikō)" },
    { kanji: "向", on: "コウ", kun: "む", meaning: "menghadap", example: "方向 (hōkō)" },
    { kanji: "矛", on: "ム", kun: "ほこ", meaning: "tombak", example: "矛盾 (mujun)" },
    { kanji: "盾", on: "ジュン", kun: "たて", meaning: "perisai", example: "矛盾 (mujun)" },
    { kanji: "依", on: "イ", kun: "—", meaning: "bergantung", example: "依存 (izon)" },
    { kanji: "存", on: "ソン", kun: "—", meaning: "ada", example: "存在 (sonzai)" },
    { kanji: "推", on: "スイ", kun: "お", meaning: "mendorong", example: "推測 (suisoku)" },
    { kanji: "測", on: "ソク", kun: "はか", meaning: "mengukur", example: "測定 (sokutei)" },
    { kanji: "詳", on: "ショウ", kun: "くわ", meaning: "rinci", example: "詳細 (shōsai)" },
    { kanji: "細", on: "サイ", kun: "ほそ", meaning: "halus", example: "詳細 (shōsai)" },
    { kanji: "範", on: "ハン", kun: "—", meaning: "lingkup", example: "範囲 (han'i)" },
    { kanji: "囲", on: "イ", kun: "かこ", meaning: "mengelilingi", example: "周囲 (shūi)" },
    { kanji: "構", on: "コウ", kun: "かま", meaning: "struktur", example: "構造 (kōzō)" },
    { kanji: "造", on: "ゾウ", kun: "つく", meaning: "membangun", example: "製造 (seizō)" },
    { kanji: "傷", on: "ショウ", kun: "きず", meaning: "luka", example: "負傷 (fushō)" },
    { kanji: "援", on: "エン", kun: "—", meaning: "membantu", example: "応援 (ōen)" },
    { kanji: "撃", on: "ゲキ", kun: "う", meaning: "menyerang", example: "攻撃 (kōgeki)" },
    { kanji: "緊", on: "キン", kun: "—", meaning: "ketat", example: "緊急 (kinkyū)" },
    { kanji: "急", on: "キュウ", kun: "いそ", meaning: "cepat", example: "急行 (kyūkō)" },
    { kanji: "貴", on: "キ", kun: "とうと", meaning: "berharga", example: "貴重 (kichō)" },
    { kanji: "貧", on: "ヒン", kun: "まず", meaning: "miskin", example: "貧困 (hinkon)" },
    { kanji: "富", on: "フ", kun: "と", meaning: "kaya", example: "富裕 (fuyū)" },
    { kanji: "豊", on: "ホウ", kun: "ゆた", meaning: "berlimpah", example: "豊富 (hōfu)" },
    { kanji: "誠", on: "セイ", kun: "まこと", meaning: "tulus", example: "誠実 (seijitsu)" },
    { kanji: "潔", on: "ケツ", kun: "いさぎよ", meaning: "bersih", example: "清潔 (seiketsu)" },
    { kanji: "純", on: "ジュン", kun: "—", meaning: "murni", example: "純粋 (junsui)" },
    { kanji: "粋", on: "スイ", kun: "—", meaning: "murni, gaya", example: "純粋 (junsui)" },
    { kanji: "雅", on: "ガ", kun: "みやび", meaning: "anggun", example: "優雅 (yūga)" },
  ],
  vocabulary: [
    { jp: "概念", romaji: "gainen", meaning: "konsep", category: "Abstrak" },
    { jp: "傾向", romaji: "keikō", meaning: "kecenderungan", category: "Abstrak" },
    { jp: "矛盾", romaji: "mujun", meaning: "kontradiksi", category: "Abstrak" },
    { jp: "依存", romaji: "izon", meaning: "ketergantungan", category: "Abstrak" },
    { jp: "推測", romaji: "suisoku", meaning: "dugaan", category: "Abstrak" },
    { jp: "達成", romaji: "tassei", meaning: "pencapaian", category: "Abstrak" },
    { jp: "貢献", romaji: "kōken", meaning: "kontribusi", category: "Abstrak" },
    { jp: "範囲", romaji: "han'i", meaning: "lingkup", category: "Abstrak" },
    { jp: "構造", romaji: "kōzō", meaning: "struktur", category: "Abstrak" },
    { jp: "詳細", romaji: "shōsai", meaning: "detail", category: "Abstrak" },
    { jp: "発揮", romaji: "hakki", meaning: "menunjukkan", category: "Kata kerja" },
    { jp: "把握", romaji: "haaku", meaning: "memahami", category: "Kata kerja" },
    { jp: "促す", romaji: "unagasu", meaning: "mendorong", category: "Kata kerja" },
    { jp: "認める", romaji: "mitomeru", meaning: "mengakui", category: "Kata kerja" },
    { jp: "示す", romaji: "shimesu", meaning: "menunjukkan", category: "Kata kerja" },
    { jp: "捉える", romaji: "toraeru", meaning: "menangkap", category: "Kata kerja" },
    { jp: "防ぐ", romaji: "fusegu", meaning: "mencegah", category: "Kata kerja" },
    { jp: "省く", romaji: "habuku", meaning: "menghemat/menghapus", category: "Kata kerja" },
    { jp: "整える", romaji: "totonoeru", meaning: "menata", category: "Kata kerja" },
    { jp: "操る", romaji: "ayatsuru", meaning: "mengendalikan", category: "Kata kerja" },
    { jp: "貴重", romaji: "kichō", meaning: "berharga", category: "Sifat" },
    { jp: "豊富", romaji: "hōfu", meaning: "berlimpah", category: "Sifat" },
    { jp: "純粋", romaji: "junsui", meaning: "murni", category: "Sifat" },
    { jp: "誠実", romaji: "seijitsu", meaning: "tulus", category: "Sifat" },
    { jp: "緊急", romaji: "kinkyū", meaning: "darurat", category: "Sifat" },
    { jp: "意外", romaji: "igai", meaning: "tak terduga", category: "Sifat" },
    { jp: "明確", romaji: "meikaku", meaning: "jelas", category: "Sifat" },
    { jp: "曖昧", romaji: "aimai", meaning: "ambigu", category: "Sifat" },
    { jp: "厳しい", romaji: "kibishii", meaning: "ketat", category: "Sifat" },
    { jp: "穏やか", romaji: "odayaka", meaning: "tenang", category: "Sifat" },
    { jp: "意識", romaji: "ishiki", meaning: "kesadaran", category: "Abstrak" },
    { jp: "無意識", romaji: "muishiki", meaning: "tanpa sadar", category: "Abstrak" },
    { jp: "印象", romaji: "inshō", meaning: "kesan", category: "Abstrak" },
    { jp: "想像", romaji: "sōzō", meaning: "imajinasi", category: "Abstrak" },
    { jp: "創造", romaji: "sōzō", meaning: "kreasi", category: "Abstrak" },
    { jp: "改善", romaji: "kaizen", meaning: "perbaikan", category: "Abstrak" },
    { jp: "悪化", romaji: "akka", meaning: "memburuk", category: "Abstrak" },
    { jp: "対応", romaji: "taiō", meaning: "tanggapan", category: "Abstrak" },
    { jp: "対策", romaji: "taisaku", meaning: "tindakan", category: "Abstrak" },
    { jp: "意義", romaji: "igi", meaning: "makna", category: "Abstrak" },
  ],
  grammar: [
    { pattern: "〜に応じて", meaning: "Sesuai dengan ~", example: "状況に応じて対応する。", exampleMeaning: "Merespons sesuai situasi." },
    { pattern: "〜を契機に", meaning: "Sebagai pemicu ~", example: "病気を契機に運動を始めた。", exampleMeaning: "Mulai olahraga karena sakit." },
    { pattern: "〜にもかかわらず", meaning: "Meskipun ~", example: "雨にもかかわらず出かけた。", exampleMeaning: "Meski hujan, tetap keluar." },
    { pattern: "〜得る", meaning: "Mungkin ~", example: "あり得る。", exampleMeaning: "Mungkin terjadi." },
    { pattern: "〜かねない", meaning: "Bisa jadi ~", example: "失敗しかねない。", exampleMeaning: "Bisa jadi gagal." },
    { pattern: "〜つつある", meaning: "Sedang dalam proses ~", example: "増えつつある。", exampleMeaning: "Sedang bertambah." },
    { pattern: "〜に限らず", meaning: "Tidak terbatas pada ~", example: "学生に限らず誰でも。", exampleMeaning: "Tidak hanya siswa." },
    { pattern: "〜どころか", meaning: "Jangankan ~", example: "走るどころか歩けない。", exampleMeaning: "Jangankan lari, jalan tak bisa." },
    { pattern: "〜に伴って", meaning: "Seiring dengan ~", example: "成長に伴って変わる。", exampleMeaning: "Berubah seiring pertumbuhan." },
    { pattern: "〜にしては", meaning: "Mengingat ~", example: "新人にしては上手だ。", exampleMeaning: "Untuk pemula, dia hebat." },
    { pattern: "〜にせよ", meaning: "Apapun ~", example: "どちらにせよ行く。", exampleMeaning: "Bagaimanapun saya pergi." },
    { pattern: "〜ものの", meaning: "Walaupun ~", example: "買ったものの使わない。", exampleMeaning: "Sudah beli, tapi tidak dipakai." },
    { pattern: "〜ばかりか", meaning: "Tidak hanya ~", example: "頭がいいばかりか優しい。", exampleMeaning: "Bukan hanya pintar, juga baik." },
    { pattern: "〜次第", meaning: "Segera setelah ~", example: "着き次第連絡します。", exampleMeaning: "Segera setelah tiba saya hubungi." },
    { pattern: "〜上で", meaning: "Setelah / dalam hal ~", example: "確認した上で決める。", exampleMeaning: "Putuskan setelah mengecek." },
    { pattern: "〜限り", meaning: "Selama ~", example: "私が知る限り。", exampleMeaning: "Sejauh yang saya tahu." },
    { pattern: "〜だらけ", meaning: "Penuh dengan ~", example: "間違いだらけ。", exampleMeaning: "Penuh kesalahan." },
    { pattern: "〜気味", meaning: "Sedikit ~", example: "風邪気味です。", exampleMeaning: "Agak masuk angin." },
    { pattern: "〜ぬきで", meaning: "Tanpa ~", example: "冗談ぬきで言う。", exampleMeaning: "Bicara serius tanpa bercanda." },
    { pattern: "〜にすぎない", meaning: "Tidak lebih dari ~", example: "言い訳にすぎない。", exampleMeaning: "Tidak lebih dari alasan." },
  ],
  sentences: [
    { jp: "彼の発言には矛盾がある。", romaji: "kare no hatsugen ni wa mujun ga aru.", meaning: "Ada kontradiksi dalam pernyataannya." },
    { jp: "状況に応じて柔軟に対応する。", romaji: "jōkyō ni ōjite jūnan ni taiō suru.", meaning: "Merespons dengan fleksibel sesuai situasi." },
    { jp: "努力にもかかわらず失敗した。", romaji: "doryoku ni mo kakawarazu shippai shita.", meaning: "Meskipun berusaha, gagal." },
    { jp: "この問題は社会全体に関わる。", romaji: "kono mondai wa shakai zentai ni kakawaru.", meaning: "Masalah ini melibatkan seluruh masyarakat." },
    { jp: "成長に伴って責任も増える。", romaji: "seichō ni tomonatte sekinin mo fueru.", meaning: "Tanggung jawab bertambah seiring pertumbuhan." },
    { jp: "彼女は新人にしては経験豊富だ。", romaji: "kanojo wa shinjin ni shite wa keiken hōfu da.", meaning: "Untuk seorang pemula, pengalamannya kaya." },
    { jp: "詳細については後ほど説明します。", romaji: "shōsai ni tsuite wa nochihodo setsumei shimasu.", meaning: "Detailnya akan saya jelaskan nanti." },
    { jp: "緊急の対応が必要です。", romaji: "kinkyū no taiō ga hitsuyō desu.", meaning: "Diperlukan tanggapan darurat." },
    { jp: "意外な結果になりました。", romaji: "igai na kekka ni narimashita.", meaning: "Hasilnya tak terduga." },
    { jp: "彼の主張には根拠がない。", romaji: "kare no shuchō ni wa konkyo ga nai.", meaning: "Argumennya tidak berdasar." },
    { jp: "目標達成のために頑張ります。", romaji: "mokuhyō tassei no tame ni ganbarimasu.", meaning: "Saya berusaha untuk mencapai target." },
    { jp: "技術の進歩は止まらない。", romaji: "gijutsu no shinpo wa tomaranai.", meaning: "Kemajuan teknologi tak terbendung." },
    { jp: "情報を慎重に扱う必要がある。", romaji: "jōhō o shinchō ni atsukau hitsuyō ga aru.", meaning: "Informasi perlu ditangani dengan hati-hati." },
    { jp: "問題は深刻化する一方だ。", romaji: "mondai wa shinkokuka suru ippō da.", meaning: "Masalah terus memburuk." },
    { jp: "彼は誠実で信頼できる人だ。", romaji: "kare wa seijitsu de shinrai dekiru hito da.", meaning: "Dia orang yang tulus dan bisa dipercaya." },
  ],
};
