import type { LevelContent } from "./types";

export const n3: LevelContent = {
  level: "N3",
  title: "JLPT N3 — Menengah",
  tagline: "Jembatan menuju kefasihan",
  description: "Pahami artikel sehari-hari, percakapan natural, dan ekspresi yang lebih nuansa.",
  hours: "450 jam",
  kanjiCount: 650,
  vocabCount: 3700,
  grammarCount: 200,
  kanji: [
    { kanji: "経", on: "ケイ", kun: "へ", meaning: "melewati", example: "経験 (keiken)" },
    { kanji: "験", on: "ケン", kun: "—", meaning: "menguji", example: "試験 (shiken)" },
    { kanji: "政", on: "セイ", kun: "—", meaning: "politik", example: "政府 (seifu)" },
    { kanji: "府", on: "フ", kun: "—", meaning: "prefektur", example: "大阪府 (ōsakafu)" },
    { kanji: "議", on: "ギ", kun: "—", meaning: "diskusi", example: "会議 (kaigi)" },
    { kanji: "民", on: "ミン", kun: "たみ", meaning: "rakyat", example: "国民 (kokumin)" },
    { kanji: "産", on: "サン", kun: "う", meaning: "produksi", example: "産業 (sangyō)" },
    { kanji: "業", on: "ギョウ", kun: "わざ", meaning: "bisnis", example: "工業 (kōgyō)" },
    { kanji: "増", on: "ゾウ", kun: "ふ", meaning: "bertambah", example: "増加 (zōka)" },
    { kanji: "減", on: "ゲン", kun: "へ", meaning: "berkurang", example: "減少 (genshō)" },
    { kanji: "感", on: "カン", kun: "—", meaning: "rasa", example: "感動 (kandō)" },
    { kanji: "情", on: "ジョウ", kun: "なさ", meaning: "emosi", example: "感情 (kanjō)" },
    { kanji: "違", on: "イ", kun: "ちが", meaning: "berbeda", example: "違反 (ihan)" },
    { kanji: "種", on: "シュ", kun: "たね", meaning: "jenis", example: "種類 (shurui)" },
    { kanji: "類", on: "ルイ", kun: "—", meaning: "kategori", example: "人類 (jinrui)" },
    { kanji: "比", on: "ヒ", kun: "くら", meaning: "membandingkan", example: "比較 (hikaku)" },
    { kanji: "較", on: "カク", kun: "—", meaning: "membandingkan", example: "比較 (hikaku)" },
    { kanji: "影", on: "エイ", kun: "かげ", meaning: "bayangan", example: "影響 (eikyō)" },
    { kanji: "響", on: "キョウ", kun: "ひび", meaning: "menggema", example: "影響 (eikyō)" },
    { kanji: "現", on: "ゲン", kun: "あらわ", meaning: "muncul", example: "現在 (genzai)" },
    { kanji: "在", on: "ザイ", kun: "あ", meaning: "ada/berada", example: "存在 (sonzai)" },
    { kanji: "過", on: "カ", kun: "す", meaning: "melewati", example: "過去 (kako) — masa lalu" },
    { kanji: "未", on: "ミ", kun: "—", meaning: "belum", example: "未来 (mirai) — masa depan" },
    { kanji: "達", on: "タツ", kun: "—", meaning: "mencapai", example: "友達 (tomodachi)" },
    { kanji: "活", on: "カツ", kun: "—", meaning: "hidup, aktif", example: "生活 (seikatsu)" },
    { kanji: "発", on: "ハツ", kun: "—", meaning: "memulai", example: "発展 (hatten)" },
    { kanji: "展", on: "テン", kun: "—", meaning: "berkembang", example: "発展 (hatten)" },
    { kanji: "確", on: "カク", kun: "たし", meaning: "yakin", example: "確認 (kakunin)" },
    { kanji: "認", on: "ニン", kun: "みと", meaning: "mengakui", example: "確認 (kakunin)" },
    { kanji: "解", on: "カイ", kun: "と", meaning: "memecahkan", example: "解決 (kaiketsu)" },
    { kanji: "決", on: "ケツ", kun: "き", meaning: "memutuskan", example: "決定 (kettei)" },
    { kanji: "答", on: "トウ", kun: "こた", meaning: "menjawab", example: "答案 (tōan)" },
    { kanji: "質", on: "シツ", kun: "—", meaning: "kualitas", example: "質問 (shitsumon)" },
    { kanji: "問", on: "モン", kun: "と", meaning: "bertanya", example: "問題 (mondai)" },
    { kanji: "題", on: "ダイ", kun: "—", meaning: "tema", example: "題目 (daimoku)" },
  ],
  vocabulary: [
    { jp: "経済", romaji: "keizai", meaning: "ekonomi", category: "Sosial" },
    { jp: "政治", romaji: "seiji", meaning: "politik", category: "Sosial" },
    { jp: "文化", romaji: "bunka", meaning: "budaya", category: "Sosial" },
    { jp: "社会", romaji: "shakai", meaning: "masyarakat", category: "Sosial" },
    { jp: "環境", romaji: "kankyō", meaning: "lingkungan", category: "Sosial" },
    { jp: "技術", romaji: "gijutsu", meaning: "teknologi", category: "Sosial" },
    { jp: "情報", romaji: "jōhō", meaning: "informasi", category: "Sosial" },
    { jp: "教育", romaji: "kyōiku", meaning: "pendidikan", category: "Sosial" },
    { jp: "歴史", romaji: "rekishi", meaning: "sejarah", category: "Sosial" },
    { jp: "経験", romaji: "keiken", meaning: "pengalaman", category: "Abstrak" },
    { jp: "意見", romaji: "iken", meaning: "pendapat", category: "Abstrak" },
    { jp: "理由", romaji: "riyū", meaning: "alasan", category: "Abstrak" },
    { jp: "原因", romaji: "gen'in", meaning: "penyebab", category: "Abstrak" },
    { jp: "結果", romaji: "kekka", meaning: "hasil", category: "Abstrak" },
    { jp: "目的", romaji: "mokuteki", meaning: "tujuan", category: "Abstrak" },
    { jp: "方法", romaji: "hōhō", meaning: "metode", category: "Abstrak" },
    { jp: "関係", romaji: "kankei", meaning: "hubungan", category: "Abstrak" },
    { jp: "影響", romaji: "eikyō", meaning: "pengaruh", category: "Abstrak" },
    { jp: "状況", romaji: "jōkyō", meaning: "situasi", category: "Abstrak" },
    { jp: "場合", romaji: "baai", meaning: "kasus, situasi", category: "Abstrak" },
    { jp: "感じる", romaji: "kanjiru", meaning: "merasa", category: "Kata kerja" },
    { jp: "比べる", romaji: "kuraberu", meaning: "membandingkan", category: "Kata kerja" },
    { jp: "確かめる", romaji: "tashikameru", meaning: "memastikan", category: "Kata kerja" },
    { jp: "守る", romaji: "mamoru", meaning: "melindungi", category: "Kata kerja" },
    { jp: "助ける", romaji: "tasukeru", meaning: "menolong", category: "Kata kerja" },
    { jp: "進む", romaji: "susumu", meaning: "maju", category: "Kata kerja" },
    { jp: "戻る", romaji: "modoru", meaning: "kembali", category: "Kata kerja" },
    { jp: "向かう", romaji: "mukau", meaning: "menuju", category: "Kata kerja" },
    { jp: "通る", romaji: "tōru", meaning: "melalui", category: "Kata kerja" },
    { jp: "渡る", romaji: "wataru", meaning: "menyeberang", category: "Kata kerja" },
    { jp: "落ちる", romaji: "ochiru", meaning: "jatuh", category: "Kata kerja" },
    { jp: "倒れる", romaji: "taoreru", meaning: "tumbang", category: "Kata kerja" },
    { jp: "壊す", romaji: "kowasu", meaning: "merusak", category: "Kata kerja" },
    { jp: "直す", romaji: "naosu", meaning: "memperbaiki", category: "Kata kerja" },
    { jp: "片付ける", romaji: "katazukeru", meaning: "merapikan", category: "Kata kerja" },
    { jp: "調べる", romaji: "shiraberu", meaning: "memeriksa", category: "Kata kerja" },
    { jp: "探す", romaji: "sagasu", meaning: "mencari", category: "Kata kerja" },
    { jp: "見つける", romaji: "mitsukeru", meaning: "menemukan", category: "Kata kerja" },
    { jp: "失う", romaji: "ushinau", meaning: "kehilangan", category: "Kata kerja" },
    { jp: "得る", romaji: "eru", meaning: "memperoleh", category: "Kata kerja" },
    { jp: "様々", romaji: "samazama", meaning: "beragam", category: "Sifat" },
    { jp: "確か", romaji: "tashika", meaning: "pasti", category: "Sifat" },
    { jp: "急に", romaji: "kyū ni", meaning: "tiba-tiba", category: "Adverbia" },
    { jp: "特に", romaji: "toku ni", meaning: "terutama", category: "Adverbia" },
    { jp: "実は", romaji: "jitsu wa", meaning: "sebenarnya", category: "Adverbia" },
    { jp: "確かに", romaji: "tashika ni", meaning: "memang", category: "Adverbia" },
    { jp: "ほとんど", romaji: "hotondo", meaning: "hampir/sebagian besar", category: "Adverbia" },
    { jp: "おそらく", romaji: "osoraku", meaning: "mungkin", category: "Adverbia" },
  ],
  grammar: [
    { pattern: "〜ばかり", meaning: "Hanya / baru saja ~", example: "食べたばかりです。", exampleMeaning: "Baru saja makan." },
    { pattern: "〜ように", meaning: "Agar ~", example: "聞こえるように話す。", exampleMeaning: "Bicara agar terdengar." },
    { pattern: "〜らしい", meaning: "Sepertinya / khas ~", example: "彼は学生らしい。", exampleMeaning: "Sepertinya dia siswa." },
    { pattern: "〜そうだ (伝聞)", meaning: "Katanya ~", example: "雨が降るそうです。", exampleMeaning: "Katanya akan hujan." },
    { pattern: "〜そうだ (様態)", meaning: "Kelihatannya ~", example: "美味しそうです。", exampleMeaning: "Kelihatan enak." },
    { pattern: "〜はず", meaning: "Seharusnya ~", example: "来るはずです。", exampleMeaning: "Seharusnya datang." },
    { pattern: "〜わけだ", meaning: "Pantas saja ~", example: "寒いわけだ。", exampleMeaning: "Pantas saja dingin." },
    { pattern: "〜ても", meaning: "Meskipun ~", example: "雨が降っても行きます。", exampleMeaning: "Meskipun hujan, tetap pergi." },
    { pattern: "〜なら", meaning: "Kalau ~", example: "日本に行くなら、京都へ。", exampleMeaning: "Kalau ke Jepang, ke Kyoto." },
    { pattern: "〜について", meaning: "Tentang ~", example: "日本について話す。", exampleMeaning: "Bicara tentang Jepang." },
    { pattern: "〜によって", meaning: "Tergantung / oleh ~", example: "人によって違う。", exampleMeaning: "Berbeda tergantung orang." },
    { pattern: "〜に対して", meaning: "Terhadap ~", example: "先生に対して失礼だ。", exampleMeaning: "Tidak sopan terhadap guru." },
    { pattern: "〜にとって", meaning: "Bagi ~", example: "私にとって大切です。", exampleMeaning: "Bagi saya penting." },
    { pattern: "〜うちに", meaning: "Selagi ~", example: "若いうちに勉強しよう。", exampleMeaning: "Belajar selagi muda." },
    { pattern: "〜とおり", meaning: "Sesuai dengan ~", example: "言ったとおりにする。", exampleMeaning: "Lakukan sesuai yang dikatakan." },
    { pattern: "〜ところ", meaning: "Saat / baru saja ~", example: "今、食べているところです。", exampleMeaning: "Sekarang sedang makan." },
    { pattern: "〜まま", meaning: "Tetap dalam keadaan ~", example: "靴を履いたまま入る。", exampleMeaning: "Masuk dengan sepatu masih dipakai." },
    { pattern: "〜ばかりでなく", meaning: "Bukan hanya ~", example: "勉強ばかりでなく運動も。", exampleMeaning: "Bukan cuma belajar, juga olahraga." },
    { pattern: "〜だけでなく", meaning: "Tidak hanya ~", example: "私だけでなく彼も。", exampleMeaning: "Bukan hanya saya, dia juga." },
    { pattern: "〜代わりに", meaning: "Sebagai ganti ~", example: "肉の代わりに魚を食べる。", exampleMeaning: "Makan ikan sebagai ganti daging." },
    { pattern: "〜ように見える", meaning: "Tampak seperti ~", example: "疲れているように見える。", exampleMeaning: "Tampak lelah." },
    { pattern: "〜にする", meaning: "Memutuskan untuk ~", example: "コーヒーにします。", exampleMeaning: "Saya pilih kopi." },
    { pattern: "〜ことにする", meaning: "Memutuskan untuk ~", example: "毎日走ることにした。", exampleMeaning: "Saya putuskan untuk lari tiap hari." },
    { pattern: "〜ことになる", meaning: "Telah ditentukan ~", example: "東京に住むことになった。", exampleMeaning: "Akhirnya pindah ke Tokyo." },
    { pattern: "〜ものだ", meaning: "Memang seharusnya ~", example: "時間は大切なものだ。", exampleMeaning: "Waktu memang berharga." },
  ],
  sentences: [
    { jp: "経験を通して成長します。", romaji: "keiken o tōshite seichō shimasu.", meaning: "Kita tumbuh melalui pengalaman." },
    { jp: "状況によって対応が変わります。", romaji: "jōkyō ni yotte taiō ga kawarimasu.", meaning: "Tanggapan berbeda tergantung situasi." },
    { jp: "彼の意見に賛成します。", romaji: "kare no iken ni sansei shimasu.", meaning: "Saya setuju dengan pendapatnya." },
    { jp: "問題の原因を調べています。", romaji: "mondai no gen'in o shirabete imasu.", meaning: "Saya sedang menyelidiki penyebab masalah." },
    { jp: "環境を守ることが大切です。", romaji: "kankyō o mamoru koto ga taisetsu desu.", meaning: "Menjaga lingkungan itu penting." },
    { jp: "若いうちにいろいろな国へ行ってみたい。", romaji: "wakai uchi ni iroirona kuni e itte mitai.", meaning: "Selagi muda, saya ingin mengunjungi berbagai negara." },
    { jp: "言われたとおりにやってみました。", romaji: "iwareta tōri ni yatte mimashita.", meaning: "Saya mencoba sesuai yang diminta." },
    { jp: "経済が悪くなる一方です。", romaji: "keizai ga waruku naru ippō desu.", meaning: "Ekonomi terus memburuk." },
    { jp: "彼女は来ないかもしれません。", romaji: "kanojo wa konai kamoshiremasen.", meaning: "Mungkin dia tidak datang." },
    { jp: "勉強すればするほど面白くなる。", romaji: "benkyō sureba suru hodo omoshiroku naru.", meaning: "Semakin belajar, semakin menarik." },
    { jp: "彼は怒っているように見えます。", romaji: "kare wa okotte iru yō ni miemasu.", meaning: "Dia tampak sedang marah." },
    { jp: "急に雨が降り出しました。", romaji: "kyū ni ame ga furi-dashimashita.", meaning: "Tiba-tiba hujan turun." },
    { jp: "失敗を恐れず挑戦しましょう。", romaji: "shippai o osorezu chōsen shimashō.", meaning: "Mari mencoba tanpa takut gagal." },
    { jp: "実はもう知っています。", romaji: "jitsu wa mō shitte imasu.", meaning: "Sebenarnya saya sudah tahu." },
    { jp: "この問題は難しすぎる。", romaji: "kono mondai wa muzukashisugiru.", meaning: "Masalah ini terlalu sulit." },
    { jp: "新しい技術が社会を変えています。", romaji: "atarashii gijutsu ga shakai o kaete imasu.", meaning: "Teknologi baru mengubah masyarakat." },
    { jp: "彼に頼むしかありません。", romaji: "kare ni tanomu shika arimasen.", meaning: "Tidak ada pilihan selain meminta padanya." },
    { jp: "私にとって家族が一番大切です。", romaji: "watashi ni totte kazoku ga ichiban taisetsu desu.", meaning: "Bagi saya keluarga yang paling penting." },
    { jp: "事故が起きた原因を調べます。", romaji: "jiko ga okita gen'in o shirabemasu.", meaning: "Kami menyelidiki penyebab kecelakaan." },
    { jp: "彼の話は本当らしいです。", romaji: "kare no hanashi wa hontō rashii desu.", meaning: "Sepertinya ceritanya benar." },
  ],
};
