import type { LevelContent } from "./types";

export const n4: LevelContent = {
  level: "N4",
  title: "JLPT N4 — Dasar",
  tagline: "Perluas kosakata dan pola tata bahasa Anda",
  description: "Pahami percakapan harian dengan kosakata yang lebih kaya dan struktur kalimat yang lebih kompleks.",
  hours: "300 jam",
  kanjiCount: 300,
  vocabCount: 1500,
  grammarCount: 100,
  kanji: [
    { kanji: "会", on: "カイ", kun: "あ", meaning: "bertemu", example: "会社 (kaisha)" },
    { kanji: "社", on: "シャ", kun: "—", meaning: "perusahaan", example: "会社員 (kaishain)" },
    { kanji: "電", on: "デン", kun: "—", meaning: "listrik", example: "電車 (densha)" },
    { kanji: "話", on: "ワ", kun: "はな", meaning: "berbicara", example: "電話 (denwa)" },
    { kanji: "駅", on: "エキ", kun: "—", meaning: "stasiun", example: "東京駅 (tōkyō-eki)" },
    { kanji: "道", on: "ドウ", kun: "みち", meaning: "jalan", example: "道路 (dōro)" },
    { kanji: "親", on: "シン", kun: "おや", meaning: "orang tua", example: "親切 (shinsetsu)" },
    { kanji: "兄", on: "ケイ", kun: "あに", meaning: "kakak laki-laki", example: "兄弟 (kyōdai)" },
    { kanji: "姉", on: "シ", kun: "あね", meaning: "kakak perempuan", example: "姉妹 (shimai)" },
    { kanji: "病", on: "ビョウ", kun: "やまい", meaning: "sakit", example: "病院 (byōin)" },
    { kanji: "薬", on: "ヤク", kun: "くすり", meaning: "obat", example: "薬局 (yakkyoku)" },
    { kanji: "売", on: "バイ", kun: "う", meaning: "menjual", example: "売店 (baiten)" },
    { kanji: "買", on: "バイ", kun: "か", meaning: "membeli", example: "買い物 (kaimono)" },
    { kanji: "新", on: "シン", kun: "あたら", meaning: "baru", example: "新聞 (shinbun)" },
    { kanji: "古", on: "コ", kun: "ふる", meaning: "lama", example: "古本 (furuhon)" },
    { kanji: "高", on: "コウ", kun: "たか", meaning: "tinggi", example: "高校 (kōkō) — SMA" },
    { kanji: "安", on: "アン", kun: "やす", meaning: "aman/murah", example: "安心 (anshin)" },
    { kanji: "多", on: "タ", kun: "おお", meaning: "banyak", example: "多分 (tabun)" },
    { kanji: "少", on: "ショウ", kun: "すこ", meaning: "sedikit", example: "少し (sukoshi)" },
    { kanji: "白", on: "ハク", kun: "しろ", meaning: "putih", example: "白い (shiroi)" },
    { kanji: "黒", on: "コク", kun: "くろ", meaning: "hitam", example: "黒い (kuroi)" },
    { kanji: "赤", on: "セキ", kun: "あか", meaning: "merah", example: "赤い (akai)" },
    { kanji: "青", on: "セイ", kun: "あお", meaning: "biru", example: "青い (aoi)" },
    { kanji: "色", on: "ショク", kun: "いろ", meaning: "warna", example: "色々 (iroiro)" },
    { kanji: "心", on: "シン", kun: "こころ", meaning: "hati", example: "心配 (shinpai)" },
    { kanji: "体", on: "タイ", kun: "からだ", meaning: "tubuh", example: "体育 (taiiku)" },
    { kanji: "頭", on: "トウ", kun: "あたま", meaning: "kepala", example: "頭痛 (zutsū)" },
    { kanji: "手", on: "シュ", kun: "て", meaning: "tangan", example: "手紙 (tegami)" },
    { kanji: "足", on: "ソク", kun: "あし", meaning: "kaki", example: "足音 (ashioto)" },
    { kanji: "目", on: "モク", kun: "め", meaning: "mata", example: "目的 (mokuteki)" },
    { kanji: "口", on: "コウ", kun: "くち", meaning: "mulut", example: "入口 (iriguchi)" },
    { kanji: "耳", on: "ジ", kun: "みみ", meaning: "telinga", example: "耳鼻科 (jibika)" },
    { kanji: "週", on: "シュウ", kun: "—", meaning: "minggu", example: "今週 (konshū)" },
    { kanji: "曜", on: "ヨウ", kun: "—", meaning: "hari (mingguan)", example: "日曜日 (nichiyōbi)" },
    { kanji: "天", on: "テン", kun: "あめ", meaning: "langit", example: "天気 (tenki)" },
    { kanji: "気", on: "キ", kun: "—", meaning: "udara, perasaan", example: "元気 (genki)" },
    { kanji: "雨", on: "ウ", kun: "あめ", meaning: "hujan", example: "雨水 (amamizu)" },
    { kanji: "雪", on: "セツ", kun: "ゆき", meaning: "salju", example: "大雪 (ōyuki)" },
    { kanji: "花", on: "カ", kun: "はな", meaning: "bunga", example: "花見 (hanami)" },
    { kanji: "魚", on: "ギョ", kun: "さかな", meaning: "ikan", example: "金魚 (kingyo)" },
  ],
  vocabulary: [
    { jp: "家族", romaji: "kazoku", meaning: "keluarga", category: "Keluarga" },
    { jp: "両親", romaji: "ryōshin", meaning: "orang tua", category: "Keluarga" },
    { jp: "兄弟", romaji: "kyōdai", meaning: "saudara", category: "Keluarga" },
    { jp: "祖父", romaji: "sofu", meaning: "kakek", category: "Keluarga" },
    { jp: "祖母", romaji: "sobo", meaning: "nenek", category: "Keluarga" },
    { jp: "おじ", romaji: "oji", meaning: "paman", category: "Keluarga" },
    { jp: "おば", romaji: "oba", meaning: "bibi", category: "Keluarga" },
    { jp: "親戚", romaji: "shinseki", meaning: "kerabat", category: "Keluarga" },
    { jp: "夫", romaji: "otto", meaning: "suami", category: "Keluarga" },
    { jp: "妻", romaji: "tsuma", meaning: "istri", category: "Keluarga" },
    { jp: "仕事", romaji: "shigoto", meaning: "pekerjaan", category: "Kerja" },
    { jp: "会議", romaji: "kaigi", meaning: "rapat", category: "Kerja" },
    { jp: "会社員", romaji: "kaishain", meaning: "karyawan", category: "Kerja" },
    { jp: "社長", romaji: "shachō", meaning: "direktur", category: "Kerja" },
    { jp: "部長", romaji: "buchō", meaning: "manajer", category: "Kerja" },
    { jp: "同僚", romaji: "dōryō", meaning: "rekan kerja", category: "Kerja" },
    { jp: "給料", romaji: "kyūryō", meaning: "gaji", category: "Kerja" },
    { jp: "休み", romaji: "yasumi", meaning: "libur", category: "Kerja" },
    { jp: "出張", romaji: "shucchō", meaning: "perjalanan dinas", category: "Kerja" },
    { jp: "残業", romaji: "zangyō", meaning: "lembur", category: "Kerja" },
    { jp: "趣味", romaji: "shumi", meaning: "hobi", category: "Hobi" },
    { jp: "旅行", romaji: "ryokō", meaning: "perjalanan", category: "Hobi" },
    { jp: "映画", romaji: "eiga", meaning: "film", category: "Hobi" },
    { jp: "音楽", romaji: "ongaku", meaning: "musik", category: "Hobi" },
    { jp: "スポーツ", romaji: "supōtsu", meaning: "olahraga", category: "Hobi" },
    { jp: "野球", romaji: "yakyū", meaning: "baseball", category: "Hobi" },
    { jp: "サッカー", romaji: "sakkā", meaning: "sepak bola", category: "Hobi" },
    { jp: "写真", romaji: "shashin", meaning: "foto", category: "Hobi" },
    { jp: "料理", romaji: "ryōri", meaning: "masakan", category: "Makanan" },
    { jp: "朝ご飯", romaji: "asagohan", meaning: "sarapan", category: "Makanan" },
    { jp: "昼ご飯", romaji: "hirugohan", meaning: "makan siang", category: "Makanan" },
    { jp: "晩ご飯", romaji: "bangohan", meaning: "makan malam", category: "Makanan" },
    { jp: "おにぎり", romaji: "onigiri", meaning: "bola nasi", category: "Makanan" },
    { jp: "寿司", romaji: "sushi", meaning: "sushi", category: "Makanan" },
    { jp: "天ぷら", romaji: "tenpura", meaning: "tempura", category: "Makanan" },
    { jp: "うどん", romaji: "udon", meaning: "udon", category: "Makanan" },
    { jp: "そば", romaji: "soba", meaning: "soba", category: "Makanan" },
    { jp: "ラーメン", romaji: "rāmen", meaning: "ramen", category: "Makanan" },
    { jp: "美味しい", romaji: "oishii", meaning: "enak", category: "Sifat" },
    { jp: "甘い", romaji: "amai", meaning: "manis", category: "Sifat" },
    { jp: "辛い", romaji: "karai", meaning: "pedas", category: "Sifat" },
    { jp: "苦い", romaji: "nigai", meaning: "pahit", category: "Sifat" },
    { jp: "酸っぱい", romaji: "suppai", meaning: "asam", category: "Sifat" },
    { jp: "難しい", romaji: "muzukashii", meaning: "sulit", category: "Sifat" },
    { jp: "簡単", romaji: "kantan", meaning: "mudah", category: "Sifat" },
    { jp: "親切", romaji: "shinsetsu", meaning: "ramah", category: "Sifat" },
    { jp: "便利", romaji: "benri", meaning: "praktis", category: "Sifat" },
    { jp: "不便", romaji: "fuben", meaning: "tidak praktis", category: "Sifat" },
    { jp: "有名", romaji: "yūmei", meaning: "terkenal", category: "Sifat" },
    { jp: "大切", romaji: "taisetsu", meaning: "penting", category: "Sifat" },
    { jp: "頑張る", romaji: "ganbaru", meaning: "berusaha", category: "Kata kerja" },
    { jp: "考える", romaji: "kangaeru", meaning: "berpikir", category: "Kata kerja" },
    { jp: "覚える", romaji: "oboeru", meaning: "mengingat", category: "Kata kerja" },
    { jp: "忘れる", romaji: "wasureru", meaning: "lupa", category: "Kata kerja" },
    { jp: "始める", romaji: "hajimeru", meaning: "memulai", category: "Kata kerja" },
    { jp: "終わる", romaji: "owaru", meaning: "selesai", category: "Kata kerja" },
    { jp: "続ける", romaji: "tsuzukeru", meaning: "melanjutkan", category: "Kata kerja" },
    { jp: "やめる", romaji: "yameru", meaning: "berhenti", category: "Kata kerja" },
    { jp: "急ぐ", romaji: "isogu", meaning: "buru-buru", category: "Kata kerja" },
    { jp: "迎える", romaji: "mukaeru", meaning: "menjemput", category: "Kata kerja" },
    { jp: "送る", romaji: "okuru", meaning: "mengantar/kirim", category: "Kata kerja" },
    { jp: "渡す", romaji: "watasu", meaning: "menyerahkan", category: "Kata kerja" },
    { jp: "もらう", romaji: "morau", meaning: "menerima", category: "Kata kerja" },
    { jp: "あげる", romaji: "ageru", meaning: "memberi", category: "Kata kerja" },
    { jp: "貸す", romaji: "kasu", meaning: "meminjamkan", category: "Kata kerja" },
    { jp: "借りる", romaji: "kariru", meaning: "meminjam", category: "Kata kerja" },
    { jp: "返す", romaji: "kaesu", meaning: "mengembalikan", category: "Kata kerja" },
    { jp: "選ぶ", romaji: "erabu", meaning: "memilih", category: "Kata kerja" },
    { jp: "決める", romaji: "kimeru", meaning: "memutuskan", category: "Kata kerja" },
    { jp: "変える", romaji: "kaeru", meaning: "mengubah", category: "Kata kerja" },
    { jp: "増える", romaji: "fueru", meaning: "bertambah", category: "Kata kerja" },
    { jp: "減る", romaji: "heru", meaning: "berkurang", category: "Kata kerja" },
  ],
  grammar: [
    { pattern: "〜てください", meaning: "Tolong lakukan ~", example: "見てください。", exampleMeaning: "Tolong lihat." },
    { pattern: "〜ている", meaning: "Sedang melakukan ~", example: "食べています。", exampleMeaning: "Sedang makan." },
    { pattern: "〜たことがある", meaning: "Pernah melakukan ~", example: "日本に行ったことがあります。", exampleMeaning: "Pernah ke Jepang." },
    { pattern: "〜なければならない", meaning: "Harus ~", example: "勉強しなければなりません。", exampleMeaning: "Harus belajar." },
    { pattern: "〜なくてもいい", meaning: "Tidak perlu ~", example: "行かなくてもいいです。", exampleMeaning: "Tidak perlu pergi." },
    { pattern: "〜てもいいです", meaning: "Boleh ~", example: "入ってもいいです。", exampleMeaning: "Boleh masuk." },
    { pattern: "〜てはいけません", meaning: "Tidak boleh ~", example: "食べてはいけません。", exampleMeaning: "Tidak boleh makan." },
    { pattern: "〜と思います", meaning: "Saya pikir ~", example: "いいと思います。", exampleMeaning: "Saya pikir bagus." },
    { pattern: "〜と言いました", meaning: "Berkata ~", example: "来ると言いました。", exampleMeaning: "Berkata akan datang." },
    { pattern: "〜つもりです", meaning: "Berniat ~", example: "行くつもりです。", exampleMeaning: "Berniat pergi." },
    { pattern: "〜ながら", meaning: "Sambil ~", example: "歌いながら歩く。", exampleMeaning: "Berjalan sambil bernyanyi." },
    { pattern: "〜たら", meaning: "Jika/setelah ~", example: "雨が降ったら、行きません。", exampleMeaning: "Jika hujan, tidak pergi." },
    { pattern: "〜ば", meaning: "Kalau ~", example: "安ければ買います。", exampleMeaning: "Kalau murah saya beli." },
    { pattern: "〜と", meaning: "Begitu ~, lalu ~", example: "春になると、花が咲く。", exampleMeaning: "Begitu musim semi, bunga mekar." },
    { pattern: "〜ても", meaning: "Meskipun ~", example: "雨が降っても行きます。", exampleMeaning: "Meski hujan, tetap pergi." },
    { pattern: "〜ので", meaning: "Karena ~", example: "暑いので窓を開けます。", exampleMeaning: "Karena panas, saya buka jendela." },
    { pattern: "〜のに", meaning: "Padahal ~", example: "勉強したのに分からない。", exampleMeaning: "Padahal sudah belajar, tetap tidak paham." },
    { pattern: "〜やすい / 〜にくい", meaning: "Mudah / sulit ~", example: "この本は読みやすい。", exampleMeaning: "Buku ini mudah dibaca." },
    { pattern: "〜すぎる", meaning: "Terlalu ~", example: "食べすぎました。", exampleMeaning: "Saya kebanyakan makan." },
    { pattern: "〜方", meaning: "Cara ~", example: "使い方が分かりません。", exampleMeaning: "Tidak tahu cara pakai." },
    { pattern: "〜たり〜たりする", meaning: "Melakukan ~ dan ~", example: "読んだり書いたりする。", exampleMeaning: "Membaca dan menulis." },
    { pattern: "〜ようと思う", meaning: "Berencana ~", example: "日本へ行こうと思います。", exampleMeaning: "Berencana ke Jepang." },
    { pattern: "〜られる (受身)", meaning: "Bentuk pasif", example: "雨に降られた。", exampleMeaning: "Saya kena hujan." },
    { pattern: "〜させる", meaning: "Bentuk kausatif (menyuruh)", example: "子供に野菜を食べさせる。", exampleMeaning: "Menyuruh anak makan sayur." },
    { pattern: "〜なくなる", meaning: "Menjadi tidak ~", example: "肉を食べなくなった。", exampleMeaning: "Jadi tidak makan daging lagi." },
  ],
  sentences: [
    { jp: "毎朝七時に起きます。", romaji: "maiasa shichi-ji ni okimasu.", meaning: "Setiap pagi saya bangun jam 7." },
    { jp: "週末は家族と過ごします。", romaji: "shūmatsu wa kazoku to sugoshimasu.", meaning: "Akhir pekan saya habiskan bersama keluarga." },
    { jp: "去年、京都へ行ったことがあります。", romaji: "kyonen, kyōto e itta koto ga arimasu.", meaning: "Tahun lalu saya pernah ke Kyoto." },
    { jp: "今、日本語を勉強しています。", romaji: "ima, nihongo o benkyō shite imasu.", meaning: "Sekarang saya sedang belajar bahasa Jepang." },
    { jp: "もう宿題をしましたか。", romaji: "mō shukudai o shimashita ka.", meaning: "Sudah mengerjakan PR?" },
    { jp: "まだしていません。", romaji: "mada shite imasen.", meaning: "Belum saya kerjakan." },
    { jp: "雨が降っているので、出かけません。", romaji: "ame ga futte iru node, dekakemasen.", meaning: "Karena hujan, saya tidak keluar." },
    { jp: "この料理は作り方が簡単です。", romaji: "kono ryōri wa tsukurikata ga kantan desu.", meaning: "Cara memasak hidangan ini mudah." },
    { jp: "辞書を貸してくれませんか。", romaji: "jisho o kashite kuremasen ka.", meaning: "Bisa pinjamkan kamus?" },
    { jp: "ここでタバコを吸ってはいけません。", romaji: "koko de tabako o sutte wa ikemasen.", meaning: "Tidak boleh merokok di sini." },
    { jp: "もう少しゆっくり話してください。", romaji: "mō sukoshi yukkuri hanashite kudasai.", meaning: "Tolong bicara sedikit lebih pelan." },
    { jp: "日本の食べ物は美味しいと思います。", romaji: "nihon no tabemono wa oishii to omoimasu.", meaning: "Menurut saya makanan Jepang enak." },
    { jp: "明日、雨が降るかもしれません。", romaji: "ashita, ame ga furu kamoshiremasen.", meaning: "Besok mungkin hujan." },
    { jp: "彼は来ると言いました。", romaji: "kare wa kuru to iimashita.", meaning: "Dia bilang akan datang." },
    { jp: "若い時、よく旅行しました。", romaji: "wakai toki, yoku ryokō shimashita.", meaning: "Waktu muda saya sering bepergian." },
    { jp: "頭が痛いので、薬を飲みました。", romaji: "atama ga itai node, kusuri o nomimashita.", meaning: "Karena pusing, saya minum obat." },
    { jp: "電車に間に合いませんでした。", romaji: "densha ni maniaimasen deshita.", meaning: "Saya tidak sempat naik keretanya." },
    { jp: "プレゼントをもらいました。", romaji: "purezento o moraimashita.", meaning: "Saya menerima hadiah." },
    { jp: "もう一度説明してください。", romaji: "mō ichido setsumei shite kudasai.", meaning: "Tolong jelaskan sekali lagi." },
    { jp: "頑張ってください。", romaji: "ganbatte kudasai.", meaning: "Semangat ya." },
  ],
};
