import type { LevelContent } from "./types";

export const n5: LevelContent = {
  level: "N5",
  title: "JLPT N5 — Pemula",
  tagline: "Langkah pertama Anda ke dalam bahasa Jepang",
  description: "Kuasai Hiragana, Katakana, dan ekspresi dasar untuk percakapan sehari-hari sederhana.",
  hours: "150 jam",
  kanjiCount: 100,
  vocabCount: 800,
  grammarCount: 80,
  kanji: [
    { kanji: "一", on: "イチ", kun: "ひと", meaning: "satu", example: "一人 (hitori) — satu orang" },
    { kanji: "二", on: "ニ", kun: "ふた", meaning: "dua", example: "二月 (nigatsu) — Februari" },
    { kanji: "三", on: "サン", kun: "み", meaning: "tiga", example: "三日 (mikka) — tanggal 3" },
    { kanji: "四", on: "シ", kun: "よん", meaning: "empat", example: "四月 (shigatsu) — April" },
    { kanji: "五", on: "ゴ", kun: "いつ", meaning: "lima", example: "五人 (gonin) — 5 orang" },
    { kanji: "六", on: "ロク", kun: "む", meaning: "enam", example: "六月 (rokugatsu) — Juni" },
    { kanji: "七", on: "シチ", kun: "なな", meaning: "tujuh", example: "七時 (shichiji) — pukul 7" },
    { kanji: "八", on: "ハチ", kun: "や", meaning: "delapan", example: "八月 (hachigatsu) — Agustus" },
    { kanji: "九", on: "キュウ", kun: "ここの", meaning: "sembilan", example: "九月 (kugatsu) — September" },
    { kanji: "十", on: "ジュウ", kun: "とお", meaning: "sepuluh", example: "十人 (jūnin) — 10 orang" },
    { kanji: "百", on: "ヒャク", kun: "もも", meaning: "seratus", example: "百円 (hyakuen) — 100 yen" },
    { kanji: "千", on: "セン", kun: "ち", meaning: "seribu", example: "千円 (sen'en) — 1000 yen" },
    { kanji: "万", on: "マン", kun: "—", meaning: "sepuluh ribu", example: "一万 (ichiman) — 10.000" },
    { kanji: "日", on: "ニチ", kun: "ひ", meaning: "hari, matahari", example: "今日 (kyō) — hari ini" },
    { kanji: "月", on: "ゲツ", kun: "つき", meaning: "bulan", example: "月曜日 (getsuyōbi) — Senin" },
    { kanji: "火", on: "カ", kun: "ひ", meaning: "api", example: "火曜日 (kayōbi) — Selasa" },
    { kanji: "水", on: "スイ", kun: "みず", meaning: "air", example: "水曜日 (suiyōbi) — Rabu" },
    { kanji: "木", on: "モク", kun: "き", meaning: "pohon", example: "木曜日 (mokuyōbi) — Kamis" },
    { kanji: "金", on: "キン", kun: "かね", meaning: "emas, uang", example: "お金 (okane) — uang" },
    { kanji: "土", on: "ド", kun: "つち", meaning: "tanah", example: "土曜日 (doyōbi) — Sabtu" },
    { kanji: "人", on: "ジン", kun: "ひと", meaning: "orang", example: "日本人 (nihonjin)" },
    { kanji: "本", on: "ホン", kun: "もと", meaning: "buku, asal", example: "日本 (nihon) — Jepang" },
    { kanji: "年", on: "ネン", kun: "とし", meaning: "tahun", example: "今年 (kotoshi) — tahun ini" },
    { kanji: "時", on: "ジ", kun: "とき", meaning: "waktu", example: "時間 (jikan) — waktu" },
    { kanji: "分", on: "フン", kun: "わ", meaning: "menit, membagi", example: "三十分 (sanjuppun)" },
    { kanji: "大", on: "ダイ", kun: "おお", meaning: "besar", example: "大学 (daigaku) — universitas" },
    { kanji: "小", on: "ショウ", kun: "ちい", meaning: "kecil", example: "小学校 (shōgakkō)" },
    { kanji: "中", on: "チュウ", kun: "なか", meaning: "tengah", example: "中国 (chūgoku) — Tiongkok" },
    { kanji: "山", on: "サン", kun: "やま", meaning: "gunung", example: "富士山 (fujisan)" },
    { kanji: "川", on: "セン", kun: "かわ", meaning: "sungai", example: "川口 (kawaguchi)" },
    { kanji: "田", on: "デン", kun: "た", meaning: "sawah", example: "田中 (tanaka)" },
    { kanji: "上", on: "ジョウ", kun: "うえ", meaning: "atas", example: "上手 (jōzu) — pandai" },
    { kanji: "下", on: "カ", kun: "した", meaning: "bawah", example: "下手 (heta) — tidak pandai" },
    { kanji: "右", on: "ウ", kun: "みぎ", meaning: "kanan", example: "右側 (migigawa) — sisi kanan" },
    { kanji: "左", on: "サ", kun: "ひだり", meaning: "kiri", example: "左手 (hidarite) — tangan kiri" },
    { kanji: "前", on: "ゼン", kun: "まえ", meaning: "depan", example: "午前 (gozen) — AM" },
    { kanji: "後", on: "ゴ", kun: "うし", meaning: "belakang", example: "午後 (gogo) — PM" },
    { kanji: "外", on: "ガイ", kun: "そと", meaning: "luar", example: "外国 (gaikoku) — luar negeri" },
    { kanji: "国", on: "コク", kun: "くに", meaning: "negara", example: "国民 (kokumin)" },
    { kanji: "学", on: "ガク", kun: "まな", meaning: "belajar", example: "学生 (gakusei) — siswa" },
    { kanji: "生", on: "セイ", kun: "い", meaning: "hidup, lahir", example: "生活 (seikatsu)" },
    { kanji: "先", on: "セン", kun: "さき", meaning: "sebelumnya", example: "先生 (sensei) — guru" },
    { kanji: "校", on: "コウ", kun: "—", meaning: "sekolah", example: "学校 (gakkō)" },
    { kanji: "車", on: "シャ", kun: "くるま", meaning: "mobil", example: "電車 (densha) — kereta" },
    { kanji: "見", on: "ケン", kun: "み", meaning: "melihat", example: "見学 (kengaku)" },
    { kanji: "聞", on: "ブン", kun: "き", meaning: "mendengar", example: "新聞 (shinbun) — koran" },
    { kanji: "行", on: "コウ", kun: "い", meaning: "pergi", example: "旅行 (ryokō)" },
    { kanji: "来", on: "ライ", kun: "く", meaning: "datang", example: "来年 (rainen) — tahun depan" },
    { kanji: "食", on: "ショク", kun: "た", meaning: "makan", example: "食事 (shokuji) — makanan" },
    { kanji: "飲", on: "イン", kun: "の", meaning: "minum", example: "飲み物 (nomimono)" },
  ],
  vocabulary: [
    // Salam
    { jp: "こんにちは", romaji: "konnichiwa", meaning: "selamat siang", category: "Salam" },
    { jp: "おはようございます", romaji: "ohayō gozaimasu", meaning: "selamat pagi", category: "Salam" },
    { jp: "こんばんは", romaji: "konbanwa", meaning: "selamat malam", category: "Salam" },
    { jp: "おやすみなさい", romaji: "oyasumi nasai", meaning: "selamat tidur", category: "Salam" },
    { jp: "さようなら", romaji: "sayōnara", meaning: "selamat tinggal", category: "Salam" },
    { jp: "ありがとう", romaji: "arigatō", meaning: "terima kasih", category: "Salam" },
    { jp: "どういたしまして", romaji: "dō itashimashite", meaning: "sama-sama", category: "Salam" },
    { jp: "すみません", romaji: "sumimasen", meaning: "permisi/maaf", category: "Salam" },
    { jp: "ごめんなさい", romaji: "gomen nasai", meaning: "maaf", category: "Salam" },
    { jp: "はじめまして", romaji: "hajimemashite", meaning: "salam kenal", category: "Salam" },
    { jp: "よろしく", romaji: "yoroshiku", meaning: "mohon bantuannya", category: "Salam" },
    { jp: "おげんきですか", romaji: "ogenki desu ka", meaning: "apa kabar?", category: "Salam" },
    { jp: "げんきです", romaji: "genki desu", meaning: "saya baik", category: "Salam" },
    { jp: "いってきます", romaji: "itte kimasu", meaning: "saya pergi dulu", category: "Salam" },
    { jp: "ただいま", romaji: "tadaima", meaning: "saya pulang", category: "Salam" },
    // Dasar
    { jp: "はい", romaji: "hai", meaning: "ya", category: "Dasar" },
    { jp: "いいえ", romaji: "iie", meaning: "tidak", category: "Dasar" },
    { jp: "そうです", romaji: "sō desu", meaning: "begitulah", category: "Dasar" },
    { jp: "ちがいます", romaji: "chigaimasu", meaning: "bukan/salah", category: "Dasar" },
    { jp: "わかります", romaji: "wakarimasu", meaning: "saya mengerti", category: "Dasar" },
    { jp: "わかりません", romaji: "wakarimasen", meaning: "saya tidak mengerti", category: "Dasar" },
    // Kata ganti
    { jp: "わたし", romaji: "watashi", meaning: "saya", category: "Kata ganti" },
    { jp: "あなた", romaji: "anata", meaning: "kamu", category: "Kata ganti" },
    { jp: "かれ", romaji: "kare", meaning: "dia (laki-laki)", category: "Kata ganti" },
    { jp: "かのじょ", romaji: "kanojo", meaning: "dia (perempuan)", category: "Kata ganti" },
    { jp: "これ", romaji: "kore", meaning: "ini", category: "Kata ganti" },
    { jp: "それ", romaji: "sore", meaning: "itu", category: "Kata ganti" },
    { jp: "あれ", romaji: "are", meaning: "itu (jauh)", category: "Kata ganti" },
    { jp: "ここ", romaji: "koko", meaning: "di sini", category: "Kata ganti" },
    { jp: "そこ", romaji: "soko", meaning: "di situ", category: "Kata ganti" },
    { jp: "あそこ", romaji: "asoko", meaning: "di sana", category: "Kata ganti" },
    // Orang
    { jp: "学生", romaji: "gakusei", meaning: "siswa", category: "Orang" },
    { jp: "先生", romaji: "sensei", meaning: "guru", category: "Orang" },
    { jp: "友達", romaji: "tomodachi", meaning: "teman", category: "Orang" },
    { jp: "家族", romaji: "kazoku", meaning: "keluarga", category: "Orang" },
    { jp: "父", romaji: "chichi", meaning: "ayah (sendiri)", category: "Orang" },
    { jp: "母", romaji: "haha", meaning: "ibu (sendiri)", category: "Orang" },
    { jp: "お父さん", romaji: "otōsan", meaning: "ayah", category: "Orang" },
    { jp: "お母さん", romaji: "okāsan", meaning: "ibu", category: "Orang" },
    { jp: "兄", romaji: "ani", meaning: "kakak laki-laki", category: "Orang" },
    { jp: "姉", romaji: "ane", meaning: "kakak perempuan", category: "Orang" },
    { jp: "弟", romaji: "otōto", meaning: "adik laki-laki", category: "Orang" },
    { jp: "妹", romaji: "imōto", meaning: "adik perempuan", category: "Orang" },
    { jp: "子供", romaji: "kodomo", meaning: "anak", category: "Orang" },
    // Benda
    { jp: "本", romaji: "hon", meaning: "buku", category: "Benda" },
    { jp: "ペン", romaji: "pen", meaning: "pena", category: "Benda" },
    { jp: "鉛筆", romaji: "enpitsu", meaning: "pensil", category: "Benda" },
    { jp: "ノート", romaji: "nōto", meaning: "buku catatan", category: "Benda" },
    { jp: "つくえ", romaji: "tsukue", meaning: "meja", category: "Benda" },
    { jp: "いす", romaji: "isu", meaning: "kursi", category: "Benda" },
    { jp: "ドア", romaji: "doa", meaning: "pintu", category: "Benda" },
    { jp: "まど", romaji: "mado", meaning: "jendela", category: "Benda" },
    { jp: "かばん", romaji: "kaban", meaning: "tas", category: "Benda" },
    { jp: "けいたい", romaji: "keitai", meaning: "ponsel", category: "Benda" },
    { jp: "時計", romaji: "tokei", meaning: "jam", category: "Benda" },
    { jp: "かさ", romaji: "kasa", meaning: "payung", category: "Benda" },
    // Makanan
    { jp: "水", romaji: "mizu", meaning: "air", category: "Makanan" },
    { jp: "お茶", romaji: "ocha", meaning: "teh", category: "Makanan" },
    { jp: "コーヒー", romaji: "kōhī", meaning: "kopi", category: "Makanan" },
    { jp: "ジュース", romaji: "jūsu", meaning: "jus", category: "Makanan" },
    { jp: "ビール", romaji: "bīru", meaning: "bir", category: "Makanan" },
    { jp: "ごはん", romaji: "gohan", meaning: "nasi", category: "Makanan" },
    { jp: "パン", romaji: "pan", meaning: "roti", category: "Makanan" },
    { jp: "肉", romaji: "niku", meaning: "daging", category: "Makanan" },
    { jp: "魚", romaji: "sakana", meaning: "ikan", category: "Makanan" },
    { jp: "やさい", romaji: "yasai", meaning: "sayur", category: "Makanan" },
    { jp: "くだもの", romaji: "kudamono", meaning: "buah", category: "Makanan" },
    { jp: "たまご", romaji: "tamago", meaning: "telur", category: "Makanan" },
    { jp: "牛乳", romaji: "gyūnyū", meaning: "susu", category: "Makanan" },
    // Hewan
    { jp: "猫", romaji: "neko", meaning: "kucing", category: "Hewan" },
    { jp: "犬", romaji: "inu", meaning: "anjing", category: "Hewan" },
    { jp: "鳥", romaji: "tori", meaning: "burung", category: "Hewan" },
    { jp: "馬", romaji: "uma", meaning: "kuda", category: "Hewan" },
    // Tempat
    { jp: "学校", romaji: "gakkō", meaning: "sekolah", category: "Tempat" },
    { jp: "大学", romaji: "daigaku", meaning: "universitas", category: "Tempat" },
    { jp: "病院", romaji: "byōin", meaning: "rumah sakit", category: "Tempat" },
    { jp: "銀行", romaji: "ginkō", meaning: "bank", category: "Tempat" },
    { jp: "駅", romaji: "eki", meaning: "stasiun", category: "Tempat" },
    { jp: "店", romaji: "mise", meaning: "toko", category: "Tempat" },
    { jp: "家", romaji: "ie", meaning: "rumah", category: "Tempat" },
    { jp: "へや", romaji: "heya", meaning: "kamar", category: "Tempat" },
    { jp: "トイレ", romaji: "toire", meaning: "toilet", category: "Tempat" },
    { jp: "こうえん", romaji: "kōen", meaning: "taman", category: "Tempat" },
    // Waktu
    { jp: "今日", romaji: "kyō", meaning: "hari ini", category: "Waktu" },
    { jp: "明日", romaji: "ashita", meaning: "besok", category: "Waktu" },
    { jp: "昨日", romaji: "kinō", meaning: "kemarin", category: "Waktu" },
    { jp: "今", romaji: "ima", meaning: "sekarang", category: "Waktu" },
    { jp: "朝", romaji: "asa", meaning: "pagi", category: "Waktu" },
    { jp: "昼", romaji: "hiru", meaning: "siang", category: "Waktu" },
    { jp: "夜", romaji: "yoru", meaning: "malam", category: "Waktu" },
    { jp: "週", romaji: "shū", meaning: "minggu", category: "Waktu" },
    { jp: "月曜日", romaji: "getsuyōbi", meaning: "Senin", category: "Waktu" },
    { jp: "火曜日", romaji: "kayōbi", meaning: "Selasa", category: "Waktu" },
    { jp: "水曜日", romaji: "suiyōbi", meaning: "Rabu", category: "Waktu" },
    { jp: "木曜日", romaji: "mokuyōbi", meaning: "Kamis", category: "Waktu" },
    { jp: "金曜日", romaji: "kin'yōbi", meaning: "Jumat", category: "Waktu" },
    { jp: "土曜日", romaji: "doyōbi", meaning: "Sabtu", category: "Waktu" },
    { jp: "日曜日", romaji: "nichiyōbi", meaning: "Minggu", category: "Waktu" },
    // Kata kerja
    { jp: "食べる", romaji: "taberu", meaning: "makan", category: "Kata kerja" },
    { jp: "飲む", romaji: "nomu", meaning: "minum", category: "Kata kerja" },
    { jp: "行く", romaji: "iku", meaning: "pergi", category: "Kata kerja" },
    { jp: "来る", romaji: "kuru", meaning: "datang", category: "Kata kerja" },
    { jp: "帰る", romaji: "kaeru", meaning: "pulang", category: "Kata kerja" },
    { jp: "見る", romaji: "miru", meaning: "melihat", category: "Kata kerja" },
    { jp: "聞く", romaji: "kiku", meaning: "mendengar/bertanya", category: "Kata kerja" },
    { jp: "話す", romaji: "hanasu", meaning: "berbicara", category: "Kata kerja" },
    { jp: "読む", romaji: "yomu", meaning: "membaca", category: "Kata kerja" },
    { jp: "書く", romaji: "kaku", meaning: "menulis", category: "Kata kerja" },
    { jp: "買う", romaji: "kau", meaning: "membeli", category: "Kata kerja" },
    { jp: "売る", romaji: "uru", meaning: "menjual", category: "Kata kerja" },
    { jp: "作る", romaji: "tsukuru", meaning: "membuat", category: "Kata kerja" },
    { jp: "使う", romaji: "tsukau", meaning: "menggunakan", category: "Kata kerja" },
    { jp: "勉強する", romaji: "benkyō suru", meaning: "belajar", category: "Kata kerja" },
    { jp: "する", romaji: "suru", meaning: "melakukan", category: "Kata kerja" },
    { jp: "ある", romaji: "aru", meaning: "ada (benda)", category: "Kata kerja" },
    { jp: "いる", romaji: "iru", meaning: "ada (makhluk)", category: "Kata kerja" },
    { jp: "起きる", romaji: "okiru", meaning: "bangun", category: "Kata kerja" },
    { jp: "寝る", romaji: "neru", meaning: "tidur", category: "Kata kerja" },
    { jp: "歩く", romaji: "aruku", meaning: "berjalan", category: "Kata kerja" },
    { jp: "走る", romaji: "hashiru", meaning: "berlari", category: "Kata kerja" },
    { jp: "立つ", romaji: "tatsu", meaning: "berdiri", category: "Kata kerja" },
    { jp: "座る", romaji: "suwaru", meaning: "duduk", category: "Kata kerja" },
    { jp: "待つ", romaji: "matsu", meaning: "menunggu", category: "Kata kerja" },
    { jp: "会う", romaji: "au", meaning: "bertemu", category: "Kata kerja" },
    { jp: "わかる", romaji: "wakaru", meaning: "mengerti", category: "Kata kerja" },
    { jp: "知る", romaji: "shiru", meaning: "tahu", category: "Kata kerja" },
    { jp: "教える", romaji: "oshieru", meaning: "mengajar", category: "Kata kerja" },
    { jp: "習う", romaji: "narau", meaning: "belajar (dari guru)", category: "Kata kerja" },
    // Sifat
    { jp: "大きい", romaji: "ōkii", meaning: "besar", category: "Sifat" },
    { jp: "小さい", romaji: "chiisai", meaning: "kecil", category: "Sifat" },
    { jp: "新しい", romaji: "atarashii", meaning: "baru", category: "Sifat" },
    { jp: "古い", romaji: "furui", meaning: "lama", category: "Sifat" },
    { jp: "高い", romaji: "takai", meaning: "tinggi/mahal", category: "Sifat" },
    { jp: "安い", romaji: "yasui", meaning: "murah", category: "Sifat" },
    { jp: "良い", romaji: "ii", meaning: "baik", category: "Sifat" },
    { jp: "悪い", romaji: "warui", meaning: "buruk", category: "Sifat" },
    { jp: "暑い", romaji: "atsui", meaning: "panas", category: "Sifat" },
    { jp: "寒い", romaji: "samui", meaning: "dingin", category: "Sifat" },
    { jp: "おいしい", romaji: "oishii", meaning: "enak", category: "Sifat" },
    { jp: "まずい", romaji: "mazui", meaning: "tidak enak", category: "Sifat" },
    { jp: "おもしろい", romaji: "omoshiroi", meaning: "menarik", category: "Sifat" },
    { jp: "つまらない", romaji: "tsumaranai", meaning: "membosankan", category: "Sifat" },
    { jp: "むずかしい", romaji: "muzukashii", meaning: "sulit", category: "Sifat" },
    { jp: "やさしい", romaji: "yasashii", meaning: "mudah/ramah", category: "Sifat" },
    { jp: "はやい", romaji: "hayai", meaning: "cepat", category: "Sifat" },
    { jp: "おそい", romaji: "osoi", meaning: "lambat/terlambat", category: "Sifat" },
    { jp: "きれい", romaji: "kirei", meaning: "cantik/bersih", category: "Sifat" },
    { jp: "しずか", romaji: "shizuka", meaning: "tenang", category: "Sifat" },
    { jp: "にぎやか", romaji: "nigiyaka", meaning: "ramai", category: "Sifat" },
    { jp: "ひま", romaji: "hima", meaning: "senggang", category: "Sifat" },
    { jp: "いそがしい", romaji: "isogashii", meaning: "sibuk", category: "Sifat" },
    { jp: "たのしい", romaji: "tanoshii", meaning: "menyenangkan", category: "Sifat" },
  ],
  grammar: [
    { pattern: "〜は〜です", meaning: "A adalah B", example: "わたしは学生です。", exampleMeaning: "Saya adalah siswa." },
    { pattern: "〜じゃありません", meaning: "Bukan ~", example: "先生じゃありません。", exampleMeaning: "Bukan guru." },
    { pattern: "〜ですか", meaning: "Apakah ~?", example: "学生ですか。", exampleMeaning: "Apakah Anda siswa?" },
    { pattern: "〜でした", meaning: "Adalah ~ (lampau)", example: "昨日は雨でした。", exampleMeaning: "Kemarin hujan." },
    { pattern: "〜の〜", meaning: "Kepemilikan / atribut", example: "わたしの本。", exampleMeaning: "Buku saya." },
    { pattern: "〜があります", meaning: "Ada ~ (benda mati)", example: "本があります。", exampleMeaning: "Ada buku." },
    { pattern: "〜がいます", meaning: "Ada ~ (makhluk hidup)", example: "猫がいます。", exampleMeaning: "Ada kucing." },
    { pattern: "〜ます", meaning: "Bentuk sopan kata kerja", example: "食べます。", exampleMeaning: "Makan." },
    { pattern: "〜ません", meaning: "Bentuk negatif sopan", example: "飲みません。", exampleMeaning: "Tidak minum." },
    { pattern: "〜ました", meaning: "Bentuk lampau sopan", example: "行きました。", exampleMeaning: "Sudah pergi." },
    { pattern: "〜ませんでした", meaning: "Tidak melakukan (lampau)", example: "食べませんでした。", exampleMeaning: "Tidak makan." },
    { pattern: "〜たいです", meaning: "Ingin ~", example: "食べたいです。", exampleMeaning: "Ingin makan." },
    { pattern: "〜ましょう", meaning: "Ayo ~", example: "行きましょう。", exampleMeaning: "Ayo pergi." },
    { pattern: "〜ませんか", meaning: "Maukah ~?", example: "食べませんか。", exampleMeaning: "Mau makan tidak?" },
    { pattern: "〜で", meaning: "Di / dengan", example: "学校で勉強します。", exampleMeaning: "Belajar di sekolah." },
    { pattern: "〜に行きます", meaning: "Pergi ke ~", example: "東京に行きます。", exampleMeaning: "Pergi ke Tokyo." },
    { pattern: "〜から〜まで", meaning: "Dari ~ sampai ~", example: "九時から五時まで。", exampleMeaning: "Dari jam 9 sampai 5." },
    { pattern: "〜と", meaning: "Dengan ~", example: "友達と話す。", exampleMeaning: "Bicara dengan teman." },
    { pattern: "〜や〜など", meaning: "~ dan ~ dll", example: "本やノートなど。", exampleMeaning: "Buku, catatan, dll." },
    { pattern: "〜が好きです", meaning: "Suka ~", example: "猫が好きです。", exampleMeaning: "Suka kucing." },
    { pattern: "〜が上手です", meaning: "Pandai ~", example: "日本語が上手です。", exampleMeaning: "Pandai bahasa Jepang." },
    { pattern: "〜より〜のほうが", meaning: "~ lebih dari ~", example: "猫より犬のほうが好きです。", exampleMeaning: "Lebih suka anjing daripada kucing." },
    { pattern: "〜ながら", meaning: "Sambil ~", example: "歌いながら歩く。", exampleMeaning: "Berjalan sambil bernyanyi." },
    { pattern: "〜てください", meaning: "Tolong ~", example: "見てください。", exampleMeaning: "Tolong lihat." },
    { pattern: "〜ています", meaning: "Sedang ~", example: "食べています。", exampleMeaning: "Sedang makan." },
  ],
  sentences: [
    { jp: "わたしの名前はあきらです。", romaji: "watashi no namae wa Akira desu.", meaning: "Nama saya Akira." },
    { jp: "あなたは日本人ですか。", romaji: "anata wa nihonjin desu ka.", meaning: "Apakah kamu orang Jepang?" },
    { jp: "いいえ、インドネシア人です。", romaji: "iie, indoneshia-jin desu.", meaning: "Tidak, saya orang Indonesia." },
    { jp: "今日は何曜日ですか。", romaji: "kyō wa nan'yōbi desu ka.", meaning: "Hari ini hari apa?" },
    { jp: "今日は月曜日です。", romaji: "kyō wa getsuyōbi desu.", meaning: "Hari ini hari Senin." },
    { jp: "今、何時ですか。", romaji: "ima, nan-ji desu ka.", meaning: "Sekarang jam berapa?" },
    { jp: "三時半です。", romaji: "san-ji han desu.", meaning: "Jam setengah empat." },
    { jp: "毎朝コーヒーを飲みます。", romaji: "maiasa kōhī o nomimasu.", meaning: "Setiap pagi saya minum kopi." },
    { jp: "学校でにほんごを勉強します。", romaji: "gakkō de nihongo o benkyō shimasu.", meaning: "Saya belajar bahasa Jepang di sekolah." },
    { jp: "本を読むのが好きです。", romaji: "hon o yomu no ga suki desu.", meaning: "Saya suka membaca buku." },
    { jp: "明日、友達と映画を見ます。", romaji: "ashita, tomodachi to eiga o mimasu.", meaning: "Besok saya menonton film bersama teman." },
    { jp: "この本はいくらですか。", romaji: "kono hon wa ikura desu ka.", meaning: "Berapa harga buku ini?" },
    { jp: "千円です。", romaji: "sen'en desu.", meaning: "Seribu yen." },
    { jp: "すみません、トイレはどこですか。", romaji: "sumimasen, toire wa doko desu ka.", meaning: "Permisi, toilet di mana?" },
    { jp: "あそこです。", romaji: "asoko desu.", meaning: "Di sana." },
    { jp: "おなかがすきました。", romaji: "onaka ga sukimashita.", meaning: "Saya lapar." },
    { jp: "何を食べたいですか。", romaji: "nani o tabetai desu ka.", meaning: "Mau makan apa?" },
    { jp: "ラーメンを食べたいです。", romaji: "rāmen o tabetai desu.", meaning: "Saya ingin makan ramen." },
    { jp: "天気がいいですね。", romaji: "tenki ga ii desu ne.", meaning: "Cuacanya bagus ya." },
    { jp: "雨が降っています。", romaji: "ame ga futte imasu.", meaning: "Sedang hujan." },
    { jp: "また明日。", romaji: "mata ashita.", meaning: "Sampai jumpa besok." },
    { jp: "気をつけて。", romaji: "ki o tsukete.", meaning: "Hati-hati di jalan." },
    { jp: "お先に失礼します。", romaji: "osaki ni shitsurei shimasu.", meaning: "Saya pamit duluan." },
    { jp: "もう一度お願いします。", romaji: "mō ichido onegaishimasu.", meaning: "Tolong sekali lagi." },
    { jp: "ゆっくり話してください。", romaji: "yukkuri hanashite kudasai.", meaning: "Tolong bicara pelan-pelan." },
  ],
};
