/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SentencesRouteImport } from './routes/sentences'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as KanjiRouteImport } from './routes/kanji'
import { Route as KanaRouteImport } from './routes/kana'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as EbooksRouteImport } from './routes/ebooks'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsPomodoroRouteImport } from './routes/tools.pomodoro'
import { Route as ToolsParticlesRouteImport } from './routes/tools.particles'
import { Route as ToolsKanjiWriteRouteImport } from './routes/tools.kanji-write'
import { Route as ToolsCountersRouteImport } from './routes/tools.counters'
import { Route as ToolsConjugationRouteImport } from './routes/tools.conjugation'
import { Route as PracticeQuizRouteImport } from './routes/practice.quiz'
import { Route as PracticeFlashcardsRouteImport } from './routes/practice.flashcards'
import { Route as LevelsLevelRouteImport } from './routes/levels.$level'
import { Route as KanaKatakanaRouteImport } from './routes/kana.katakana'
import { Route as KanaHiraganaRouteImport } from './routes/kana.hiragana'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SentencesRoute = SentencesRouteImport.update({
  id: '/sentences',
  path: '/sentences',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjiRoute = KanjiRouteImport.update({
  id: '/kanji',
  path: '/kanji',
  getParentRoute: () => rootRouteImport,
} as any)
const KanaRoute = KanaRouteImport.update({
  id: '/kana',
  path: '/kana',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksRoute = EbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPomodoroRoute = ToolsPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsParticlesRoute = ToolsParticlesRouteImport.update({
  id: '/particles',
  path: '/particles',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsKanjiWriteRoute = ToolsKanjiWriteRouteImport.update({
  id: '/kanji-write',
  path: '/kanji-write',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCountersRoute = ToolsCountersRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsConjugationRoute = ToolsConjugationRouteImport.update({
  id: '/conjugation',
  path: '/conjugation',
  getParentRoute: () => ToolsRoute,
} as any)
const PracticeQuizRoute = PracticeQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeFlashcardsRoute = PracticeFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => PracticeRoute,
} as any)
const LevelsLevelRoute = LevelsLevelRouteImport.update({
  id: '/$level',
  path: '/$level',
  getParentRoute: () => LevelsRoute,
} as any)
const KanaKatakanaRoute = KanaKatakanaRouteImport.update({
  id: '/katakana',
  path: '/katakana',
  getParentRoute: () => KanaRoute,
} as any)
const KanaHiraganaRoute = KanaHiraganaRouteImport.update({
  id: '/hiragana',
  path: '/hiragana',
  getParentRoute: () => KanaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/bookmarks': typeof BookmarksRoute
  '/ebooks': typeof EbooksRoute
  '/exam': typeof ExamRoute
  '/grammar': typeof GrammarRoute
  '/kana': typeof KanaRouteWithChildren
  '/kanji': typeof KanjiRoute
  '/levels': typeof LevelsRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/reader': typeof ReaderRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/sentences': typeof SentencesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/topics': typeof TopicsRoute
  '/vocabulary': typeof VocabularyRoute
  '/kana/hiragana': typeof KanaHiraganaRoute
  '/kana/katakana': typeof KanaKatakanaRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/practice/flashcards': typeof PracticeFlashcardsRoute
  '/practice/quiz': typeof PracticeQuizRoute
  '/tools/conjugation': typeof ToolsConjugationRoute
  '/tools/counters': typeof ToolsCountersRoute
  '/tools/kanji-write': typeof ToolsKanjiWriteRoute
  '/tools/particles': typeof ToolsParticlesRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/bookmarks': typeof BookmarksRoute
  '/ebooks': typeof EbooksRoute
  '/exam': typeof ExamRoute
  '/grammar': typeof GrammarRoute
  '/kana': typeof KanaRouteWithChildren
  '/kanji': typeof KanjiRoute
  '/levels': typeof LevelsRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/reader': typeof ReaderRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/sentences': typeof SentencesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/topics': typeof TopicsRoute
  '/vocabulary': typeof VocabularyRoute
  '/kana/hiragana': typeof KanaHiraganaRoute
  '/kana/katakana': typeof KanaKatakanaRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/practice/flashcards': typeof PracticeFlashcardsRoute
  '/practice/quiz': typeof PracticeQuizRoute
  '/tools/conjugation': typeof ToolsConjugationRoute
  '/tools/counters': typeof ToolsCountersRoute
  '/tools/kanji-write': typeof ToolsKanjiWriteRoute
  '/tools/particles': typeof ToolsParticlesRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/bookmarks': typeof BookmarksRoute
  '/ebooks': typeof EbooksRoute
  '/exam': typeof ExamRoute
  '/grammar': typeof GrammarRoute
  '/kana': typeof KanaRouteWithChildren
  '/kanji': typeof KanjiRoute
  '/levels': typeof LevelsRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/reader': typeof ReaderRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/sentences': typeof SentencesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/topics': typeof TopicsRoute
  '/vocabulary': typeof VocabularyRoute
  '/kana/hiragana': typeof KanaHiraganaRoute
  '/kana/katakana': typeof KanaKatakanaRoute
  '/levels/$level': typeof LevelsLevelRoute
  '/practice/flashcards': typeof PracticeFlashcardsRoute
  '/practice/quiz': typeof PracticeQuizRoute
  '/tools/conjugation': typeof ToolsConjugationRoute
  '/tools/counters': typeof ToolsCountersRoute
  '/tools/kanji-write': typeof ToolsKanjiWriteRoute
  '/tools/particles': typeof ToolsParticlesRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/bookmarks'
    | '/ebooks'
    | '/exam'
    | '/grammar'
    | '/kana'
    | '/kanji'
    | '/levels'
    | '/practice'
    | '/reader'
    | '/review'
    | '/search'
    | '/sentences'
    | '/tools'
    | '/topics'
    | '/vocabulary'
    | '/kana/hiragana'
    | '/kana/katakana'
    | '/levels/$level'
    | '/practice/flashcards'
    | '/practice/quiz'
    | '/tools/conjugation'
    | '/tools/counters'
    | '/tools/kanji-write'
    | '/tools/particles'
    | '/tools/pomodoro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/bookmarks'
    | '/ebooks'
    | '/exam'
    | '/grammar'
    | '/kana'
    | '/kanji'
    | '/levels'
    | '/practice'
    | '/reader'
    | '/review'
    | '/search'
    | '/sentences'
    | '/tools'
    | '/topics'
    | '/vocabulary'
    | '/kana/hiragana'
    | '/kana/katakana'
    | '/levels/$level'
    | '/practice/flashcards'
    | '/practice/quiz'
    | '/tools/conjugation'
    | '/tools/counters'
    | '/tools/kanji-write'
    | '/tools/particles'
    | '/tools/pomodoro'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/bookmarks'
    | '/ebooks'
    | '/exam'
    | '/grammar'
    | '/kana'
    | '/kanji'
    | '/levels'
    | '/practice'
    | '/reader'
    | '/review'
    | '/search'
    | '/sentences'
    | '/tools'
    | '/topics'
    | '/vocabulary'
    | '/kana/hiragana'
    | '/kana/katakana'
    | '/levels/$level'
    | '/practice/flashcards'
    | '/practice/quiz'
    | '/tools/conjugation'
    | '/tools/counters'
    | '/tools/kanji-write'
    | '/tools/particles'
    | '/tools/pomodoro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  BookmarksRoute: typeof BookmarksRoute
  EbooksRoute: typeof EbooksRoute
  ExamRoute: typeof ExamRoute
  GrammarRoute: typeof GrammarRoute
  KanaRoute: typeof KanaRouteWithChildren
  KanjiRoute: typeof KanjiRoute
  LevelsRoute: typeof LevelsRouteWithChildren
  PracticeRoute: typeof PracticeRouteWithChildren
  ReaderRoute: typeof ReaderRoute
  ReviewRoute: typeof ReviewRoute
  SearchRoute: typeof SearchRoute
  SentencesRoute: typeof SentencesRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  TopicsRoute: typeof TopicsRoute
  VocabularyRoute: typeof VocabularyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentences': {
      id: '/sentences'
      path: '/sentences'
      fullPath: '/sentences'
      preLoaderRoute: typeof SentencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanji': {
      id: '/kanji'
      path: '/kanji'
      fullPath: '/kanji'
      preLoaderRoute: typeof KanjiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kana': {
      id: '/kana'
      path: '/kana'
      fullPath: '/kana'
      preLoaderRoute: typeof KanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks': {
      id: '/ebooks'
      path: '/ebooks'
      fullPath: '/ebooks'
      preLoaderRoute: typeof EbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pomodoro': {
      id: '/tools/pomodoro'
      path: '/pomodoro'
      fullPath: '/tools/pomodoro'
      preLoaderRoute: typeof ToolsPomodoroRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/particles': {
      id: '/tools/particles'
      path: '/particles'
      fullPath: '/tools/particles'
      preLoaderRoute: typeof ToolsParticlesRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/kanji-write': {
      id: '/tools/kanji-write'
      path: '/kanji-write'
      fullPath: '/tools/kanji-write'
      preLoaderRoute: typeof ToolsKanjiWriteRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/counters': {
      id: '/tools/counters'
      path: '/counters'
      fullPath: '/tools/counters'
      preLoaderRoute: typeof ToolsCountersRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/conjugation': {
      id: '/tools/conjugation'
      path: '/conjugation'
      fullPath: '/tools/conjugation'
      preLoaderRoute: typeof ToolsConjugationRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/practice/quiz': {
      id: '/practice/quiz'
      path: '/quiz'
      fullPath: '/practice/quiz'
      preLoaderRoute: typeof PracticeQuizRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/flashcards': {
      id: '/practice/flashcards'
      path: '/flashcards'
      fullPath: '/practice/flashcards'
      preLoaderRoute: typeof PracticeFlashcardsRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/levels/$level': {
      id: '/levels/$level'
      path: '/$level'
      fullPath: '/levels/$level'
      preLoaderRoute: typeof LevelsLevelRouteImport
      parentRoute: typeof LevelsRoute
    }
    '/kana/katakana': {
      id: '/kana/katakana'
      path: '/katakana'
      fullPath: '/kana/katakana'
      preLoaderRoute: typeof KanaKatakanaRouteImport
      parentRoute: typeof KanaRoute
    }
    '/kana/hiragana': {
      id: '/kana/hiragana'
      path: '/hiragana'
      fullPath: '/kana/hiragana'
      preLoaderRoute: typeof KanaHiraganaRouteImport
      parentRoute: typeof KanaRoute
    }
  }
}

interface KanaRouteChildren {
  KanaHiraganaRoute: typeof KanaHiraganaRoute
  KanaKatakanaRoute: typeof KanaKatakanaRoute
}

const KanaRouteChildren: KanaRouteChildren = {
  KanaHiraganaRoute: KanaHiraganaRoute,
  KanaKatakanaRoute: KanaKatakanaRoute,
}

const KanaRouteWithChildren = KanaRoute._addFileChildren(KanaRouteChildren)

interface LevelsRouteChildren {
  LevelsLevelRoute: typeof LevelsLevelRoute
}

const LevelsRouteChildren: LevelsRouteChildren = {
  LevelsLevelRoute: LevelsLevelRoute,
}

const LevelsRouteWithChildren =
  LevelsRoute._addFileChildren(LevelsRouteChildren)

interface PracticeRouteChildren {
  PracticeFlashcardsRoute: typeof PracticeFlashcardsRoute
  PracticeQuizRoute: typeof PracticeQuizRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeFlashcardsRoute: PracticeFlashcardsRoute,
  PracticeQuizRoute: PracticeQuizRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

interface ToolsRouteChildren {
  ToolsConjugationRoute: typeof ToolsConjugationRoute
  ToolsCountersRoute: typeof ToolsCountersRoute
  ToolsKanjiWriteRoute: typeof ToolsKanjiWriteRoute
  ToolsParticlesRoute: typeof ToolsParticlesRoute
  ToolsPomodoroRoute: typeof ToolsPomodoroRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsConjugationRoute: ToolsConjugationRoute,
  ToolsCountersRoute: ToolsCountersRoute,
  ToolsKanjiWriteRoute: ToolsKanjiWriteRoute,
  ToolsParticlesRoute: ToolsParticlesRoute,
  ToolsPomodoroRoute: ToolsPomodoroRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  BookmarksRoute: BookmarksRoute,
  EbooksRoute: EbooksRoute,
  ExamRoute: ExamRoute,
  GrammarRoute: GrammarRoute,
  KanaRoute: KanaRouteWithChildren,
  KanjiRoute: KanjiRoute,
  LevelsRoute: LevelsRouteWithChildren,
  PracticeRoute: PracticeRouteWithChildren,
  ReaderRoute: ReaderRoute,
  ReviewRoute: ReviewRoute,
  SearchRoute: SearchRoute,
  SentencesRoute: SentencesRoute,
  ToolsRoute: ToolsRouteWithChildren,
  TopicsRoute: TopicsRoute,
  VocabularyRoute: VocabularyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
